/* =========================================================
   AUTH PAGE BUILDER - DOWNLOAD PACKAGE GENERATOR
   File: js/download.js
========================================================= */

(function (root, factory) {
  if (typeof module !== "undefined" && module.exports) {
    const templates = require("./templates.js");
    const renderer = require("./renderer.js");
    const utils = require("./utils.js");
    const constants = require("./constants.js");
    module.exports = factory(templates, renderer, utils, constants);
  } else {
    const downloadManager = factory(root.Templates, root.AuthPageRenderer, root.Utils, root.Constants);
    root.DownloadManager = downloadManager;
    root.downloadPackage = downloadManager.downloadPackage;
  }
})(typeof window !== "undefined" ? window : globalThis, function (Templates, Renderer, Utils, Constants) {

  function getCleanConfig() {
    const rootState = (typeof window !== "undefined" && window.state) ? window.state : (typeof globalThis !== "undefined" && globalThis.state ? globalThis.state : null);
    if (rootState && typeof rootState.serializeCurrentConfiguration === "function") {
      return JSON.parse(JSON.stringify(rootState.serializeCurrentConfiguration()));
    }
    if (rootState && typeof rootState.getState === "function") {
      return JSON.parse(JSON.stringify(rootState.getState()));
    }
    const fallback = (typeof window !== "undefined" && window.config) ? window.config : (typeof globalThis !== "undefined" ? globalThis.config : {});
    return JSON.parse(JSON.stringify(fallback || {}));
  }

  /* =======================================================
     FETCH LOCAL ASSET AS ARRAYBUFFER
  ======================================================= */
  async function fetchAsset(url) {
    try {
      const isNode = typeof process !== "undefined" && process.versions && process.versions.node;
      if (isNode || typeof window === "undefined") {
        // Node environment fallback for testing & CLI builds
        const fs = require("fs");
        const path = require("path");
        const cleanPath = url.replace(/^\.\//, "").replace(/^\//, "");
        const fullPath = path.resolve(__dirname, "..", cleanPath);
        if (fs.existsSync(fullPath)) {
          return fs.readFileSync(fullPath);
        }
      }
      if (typeof fetch !== "undefined") {
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return await response.arrayBuffer();
      }
    } catch (e) {
      console.warn(`Could not fetch asset ${url}:`, e.message || e);
    }
    return null;
  }

  /* =======================================================
     DETECT MIME TYPE AND EXTENSION FROM DATA URL
  ======================================================= */
  function detectMimeAndExt(dataUrl, fallbackExt = "png") {
    if (!dataUrl || typeof dataUrl !== "string" || !dataUrl.startsWith("data:")) {
      return { mime: "image/png", ext: fallbackExt };
    }
    const header = dataUrl.split(",")[0].toLowerCase();
    if (header.includes("image/svg+xml")) return { mime: "image/svg+xml", ext: "svg" };
    if (header.includes("image/webp")) return { mime: "image/webp", ext: "webp" };
    if (header.includes("image/jpeg") || header.includes("image/jpg")) return { mime: "image/jpeg", ext: "jpg" };
    if (header.includes("image/png")) return { mime: "image/png", ext: "png" };
    if (header.includes("image/gif")) return { mime: "image/gif", ext: "gif" };
    return { mime: "image/png", ext: fallbackExt };
  }

  /* =======================================================
     STANDALONE CSS GENERATOR
  ======================================================= */
  function generateStandaloneCSS(config) {
    const dynamicVars = Renderer ? Renderer.computeStyleVariables(config, { fromFile: "css/styles.css" }) : "";
    
    return `/* =========================================================
   AUTH PAGE - STANDALONE STYLESHEET
   Generated by Auth Page Builder
========================================================= */

${dynamicVars}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html, body {
  width: 100%;
  height: 100%;
  font-family: var(--auth-font-family, 'Inter', -apple-system, BlinkMacSystemFont, sans-serif);
  color: var(--auth-title-color, #0f172a);
  background-color: var(--auth-background-color, #0f172a);
  -webkit-font-smoothing: antialiased;
}

.auth-preview-root {
  width: 100vw;
  min-height: 100vh;
  position: relative;
  overflow-x: hidden;
  background-color: var(--auth-background-color, #0f172a);
}

.auth-preview-shell {
  width: 100%;
  min-height: 100vh;
  display: flex;
  position: relative;
}

/* Layouts */
.auth-preview-root.layout-split-left-image .auth-preview-shell { flex-direction: row; }
.auth-preview-root.layout-split-right-image .auth-preview-shell { flex-direction: row-reverse; }

.auth-preview-root.layout-centered { background-color: var(--auth-background-color, #f8fafc); }
.auth-preview-root.layout-centered .auth-image-section { display: none !important; }
.auth-preview-root.layout-centered .auth-form-section { width: 100%; background: transparent; }

.auth-preview-root.layout-full-background,
.layout-full-background {
  position: relative;
  width: 100%;
  min-height: 100vh;
  overflow: hidden;
  background-color: var(--auth-background-color, #0f172a);
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}

.layout-full-background .auth-full-background {
  position: absolute;
  inset: 0;
  z-index: 0;
  background-color: var(--auth-background-color, #0f172a);
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}

.layout-full-background .auth-full-background-overlay,
.auth-preview-root.layout-full-background::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-full-background .auth-image-section { display: none !important; }
.layout-full-background .auth-background-text,
.auth-preview-root.layout-full-background .auth-background-text {
  position: absolute;
  inset: 0;
  z-index: 2;
  display: flex;
  padding: clamp(24px, 4vw, 56px);
  pointer-events: none;
}
.layout-full-background .auth-background-text .auth-image-text-block {
  pointer-events: auto;
  max-width: 520px;
}
.auth-preview-root.layout-full-background .auth-form-section,
.layout-full-background .auth-form-section { width: 100%; z-index: 3; background: transparent !important; }

.auth-preview-root.layout-minimal { background-color: #ffffff; }
.auth-preview-root.layout-minimal .auth-image-section { display: none !important; }
.auth-preview-root.layout-minimal .auth-form-section { width: 100%; background: #ffffff; }
.auth-preview-root.layout-minimal .auth-card {
  border: none !important;
  box-shadow: none !important;
  background: transparent !important;
  backdrop-filter: none !important;
  padding: 24px 0 !important;
}

.auth-preview-root.layout-card-left {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}
.auth-preview-root.layout-card-left::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-card-left .auth-image-section { display: none !important; }
.auth-preview-root.layout-card-left .auth-form-section { width: 100%; z-index: 2; background: transparent; justify-content: flex-start; padding-left: clamp(32px, 8vw, 120px); }

.auth-preview-root.layout-card-right {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}
.auth-preview-root.layout-card-right::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-card-right .auth-image-section { display: none !important; }
.auth-preview-root.layout-card-right .auth-form-section { width: 100%; z-index: 2; background: transparent; justify-content: flex-end; padding-right: clamp(32px, 8vw, 120px); }

/* Background Section */
.auth-image-section {
  flex: 0 0 var(--auth-image-width, 50%);
  width: var(--auth-image-width, 50%);
  min-height: 100vh;
  position: relative;
  display: flex;
  overflow: hidden;
  background-color: var(--auth-background-color, #0f172a);
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}

.auth-image-overlay {
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}

.auth-image-content,
.auth-background-text {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  z-index: 2;
  display: flex;
  flex-direction: column;
  padding: clamp(24px, 4vw, 56px);
  pointer-events: none;
  box-sizing: border-box;
}
.auth-image-content.position-top-left, .auth-background-text.position-top-left { justify-content: flex-start; align-items: flex-start; text-align: left; }
.auth-image-content.position-top-center, .auth-image-content.position-top, .auth-background-text.position-top-center, .auth-background-text.position-top { justify-content: flex-start; align-items: center; text-align: center; }
.auth-image-content.position-top-right, .auth-background-text.position-top-right { justify-content: flex-start; align-items: flex-end; text-align: right; }
.auth-image-content.position-center-left, .auth-image-content.position-left, .auth-background-text.position-center-left, .auth-background-text.position-left { justify-content: center; align-items: flex-start; text-align: left; }
.auth-image-content.position-center, .auth-background-text.position-center { justify-content: center; align-items: center; text-align: center; }
.auth-image-content.position-center-right, .auth-image-content.position-right, .auth-background-text.position-center-right, .auth-background-text.position-right { justify-content: center; align-items: flex-end; text-align: right; }
.auth-image-content.position-bottom-left, .auth-background-text.position-bottom-left { justify-content: flex-end; align-items: flex-start; text-align: left; }
.auth-image-content.position-bottom-center, .auth-image-content.position-bottom, .auth-background-text.position-bottom-center, .auth-background-text.position-bottom { justify-content: flex-end; align-items: center; text-align: center; }
.auth-image-content.position-bottom-right, .auth-background-text.position-bottom-right { justify-content: flex-end; align-items: flex-end; text-align: right; }
.auth-image-content.position-bottom-left { align-items: flex-end; justify-content: flex-start; text-align: left; }
.auth-image-content.position-bottom-center { align-items: flex-end; justify-content: center; text-align: center; }
.auth-image-content.position-bottom-right { align-items: flex-end; justify-content: flex-end; text-align: right; }

.auth-image-text-block { max-width: 480px; }
.auth-image-text {
  margin: 0 0 12px;
  color: var(--auth-image-text-color, #ffffff);
  font-size: clamp(22px, 3vw, 40px);
  font-weight: 800;
  line-height: 1.2;
  letter-spacing: -0.03em;
  text-shadow: 0 4px 16px rgba(0, 0, 0, 0.35);
}
.auth-image-subtext {
  margin: 0;
  color: var(--auth-image-text-color, #ffffff);
  opacity: 0.85;
  font-size: 15px;
  line-height: 1.6;
}

/* Form Section */
.auth-form-section {
  flex: 1 1 auto;
  min-width: 0;
  min-height: 0;
  width: 100%;
  height: 100%;
  display: flex !important;
  flex-direction: column !important;
  overflow-y: auto !important;
  overflow-x: hidden !important;
  padding: clamp(24px, 4vh, 48px) clamp(16px, 3vw, 36px) !important;
  background-color: #f8fafc;
  box-sizing: border-box !important;
}

.auth-form-section::before {
  content: "";
  display: block;
  flex: 1 0 auto;
  min-height: 0;
  pointer-events: none;
}
.auth-form-section::after {
  content: "";
  display: block;
  flex: 1 0 auto;
  min-height: 0;
  pointer-events: none;
}

.auth-preview-root.form-horizontal-left .auth-form-section { align-items: flex-start !important; }
.auth-preview-root.form-horizontal-center .auth-form-section { align-items: center !important; }
.auth-preview-root.form-horizontal-right .auth-form-section { align-items: flex-end !important; }

.auth-preview-root.form-vertical-top .auth-form-section::before { display: none !important; flex: 0 0 0px !important; }
.auth-preview-root.form-vertical-top .auth-form-section::after { display: block !important; flex: 1 0 auto !important; }
.auth-preview-root.form-vertical-top .auth-card { margin-top: 0 !important; margin-bottom: auto !important; }

.auth-preview-root.form-vertical-center .auth-form-section::before { display: block !important; flex: 1 0 auto !important; }
.auth-preview-root.form-vertical-center .auth-form-section::after { display: block !important; flex: 1 0 auto !important; }
.auth-preview-root.form-vertical-center .auth-card { margin-top: auto !important; margin-bottom: auto !important; }

.auth-preview-root.form-vertical-bottom .auth-form-section::before { display: block !important; flex: 1 0 auto !important; }
.auth-preview-root.form-vertical-bottom .auth-form-section::after { display: none !important; flex: 0 0 0px !important; }
.auth-preview-root.form-vertical-bottom .auth-card { margin-top: auto !important; margin-bottom: 0 !important; }

/* Card */
.auth-card {
  width: min(100%, var(--auth-card-width, 460px));
  max-width: var(--auth-card-width, 460px);
  min-height: var(--auth-card-min-height, 0px);
  height: auto !important;
  max-height: none !important;
  padding: clamp(20px, 3vh, var(--auth-card-padding, 36px)) clamp(20px, 3vw, var(--auth-card-padding, 36px));
  border-radius: var(--auth-card-radius, 20px);
  background-color: var(--auth-card-background, #ffffff);
  opacity: var(--auth-card-opacity, 1);
  border: var(--auth-card-border-width, 1px) solid var(--auth-card-border-color, #e2e8f0);
  box-shadow: var(--auth-card-shadow, 0 20px 45px rgba(15, 23, 42, 0.10));
  backdrop-filter: blur(var(--auth-card-blur, 0px));
  -webkit-backdrop-filter: blur(var(--auth-card-blur, 0px));
  position: relative;
  z-index: 4;
  flex-shrink: 0;
  box-sizing: border-box !important;
  overflow: hidden !important;
}

.auth-landing-link-bar { margin-bottom: 20px; }
.auth-landing-link {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: #64748b;
  font-size: 13.5px;
  font-weight: 500;
  text-decoration: none;
  transition: color 0.15s ease;
}
.auth-landing-link:hover { color: #2563eb; }

/* Logo & Branding */
.auth-branding-header {
  display: flex;
  flex-direction: column;
  margin-bottom: 22px;
}
.auth-branding-header.auth-logo-pos-left { align-items: flex-start; text-align: left; }
.auth-branding-header.auth-logo-pos-center { align-items: center; text-align: center; }
.auth-branding-header.auth-logo-pos-right { align-items: flex-end; text-align: right; }

.auth-logo-box {
  width: var(--auth-logo-size, 64px);
  height: var(--auth-logo-size, 64px);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  margin-bottom: 10px;
  background-color: var(--auth-logo-bg, transparent);
  border-radius: var(--auth-logo-radius, 50%);
  clip-path: var(--auth-logo-clip, none);
  -webkit-clip-path: var(--auth-logo-clip, none);
  flex-shrink: 0;
}

.auth-logo-shape-square { border-radius: 0px !important; clip-path: none !important; -webkit-clip-path: none !important; width: var(--auth-logo-size, 64px); height: var(--auth-logo-size, 64px); }
.auth-logo-shape-rounded { border-radius: 14px !important; clip-path: none !important; -webkit-clip-path: none !important; width: var(--auth-logo-size, 64px); height: var(--auth-logo-size, 64px); }
.auth-logo-shape-circle { border-radius: 50% !important; clip-path: circle(50% at 50% 50%) !important; -webkit-clip-path: circle(50% at 50% 50%) !important; width: var(--auth-logo-size, 64px); height: var(--auth-logo-size, 64px); }
.auth-logo-shape-ellipse { border-radius: 50% !important; clip-path: ellipse(50% 38% at 50% 50%) !important; -webkit-clip-path: ellipse(50% 38% at 50% 50%) !important; width: calc(var(--auth-logo-size, 64px) * 1.35) !important; height: var(--auth-logo-size, 64px); }

.auth-logo-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.auth-logo-fallback {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #2563eb, #4f46e5);
  color: #ffffff;
  font-weight: 800;
  font-size: calc(var(--auth-logo-size, 64px) * 0.38);
}

.auth-brand-title {
  font-size: 16px;
  font-weight: 700;
  color: var(--auth-title-color, #0f172a);
}

/* Typography */
.auth-form-header { margin-bottom: 22px; }
.auth-heading {
  margin: 0 0 8px;
  color: var(--auth-title-color, #0f172a);
  font-size: var(--auth-title-size, 32px);
  font-weight: var(--auth-title-weight, 700);
  line-height: 1.25;
  letter-spacing: -0.02em;
}
.auth-subheading {
  margin: 0;
  color: var(--auth-subtitle-color, #64748b);
  font-size: var(--auth-subtitle-size, 15px);
  line-height: 1.5;
}

/* Forms */
.auth-main-form { display: flex; flex-direction: column; gap: 18px; }
.auth-field-group { display: flex; flex-direction: column; gap: 7px; text-align: left; }
.auth-label-row { display: flex; align-items: center; justify-content: space-between; }
.auth-label { font-size: 13.5px; font-weight: 600; color: var(--auth-label-color, #475569); }
.auth-input-wrapper { position: relative; display: flex; align-items: center; width: 100%; }
.auth-input {
  width: 100%;
  height: 46px;
  padding: 0 14px;
  font-family: inherit;
  font-size: 14.5px;
  color: var(--auth-body-color, #0f172a);
  background-color: #ffffff;
  border: 1.5px solid #cbd5e1;
  border-radius: 10px;
  outline: none;
}
.auth-input:focus {
  border-color: #2563eb;
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.14);
}
.auth-input-password-wrapper .auth-input { padding-right: 42px; }
.auth-password-toggle {
  position: absolute;
  right: 12px;
  background: none;
  border: none;
  padding: 4px;
  cursor: pointer;
  color: #64748b;
}
.password-strength-bar {
  height: 4px;
  background: #e2e8f0;
  border-radius: 2px;
  overflow: hidden;
  margin-top: 4px;
}
.password-strength-fill { height: 100%; background: #10b981; }

.auth-checkbox-group { display: flex; align-items: center; margin-top: -4px; }
.auth-checkbox-label { display: inline-flex; align-items: center; gap: 8px; font-size: 13.5px; color: #475569; cursor: pointer; }
.auth-checkbox { width: 17px; height: 17px; accent-color: #2563eb; }

/* Buttons */
.auth-primary-btn {
  width: 100%;
  height: var(--auth-button-height, 48px);
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 0 20px;
  background: var(--auth-button-bg, #2563eb);
  color: var(--auth-button-text, #ffffff);
  border: none;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 15px;
  font-weight: 650;
  cursor: pointer;
  box-shadow: var(--auth-button-shadow, 0 4px 14px rgba(37, 99, 235, 0.28));
  transition: all 0.15s ease;
}
.auth-primary-btn:hover {
  filter: brightness(1.06);
  transform: translateY(-1px);
}

.auth-secondary-btn {
  width: 100%;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: #f1f5f9;
  color: #334155;
  border: 1px solid #e2e8f0;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
}
.auth-secondary-btn:hover { background: #e2e8f0; color: #0f172a; }

.auth-whatsapp-btn {
  width: 100%;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: #f0fdf4;
  color: #15803d;
  border: 1.5px solid #bbf7d0;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 14px;
  font-weight: 650;
  cursor: pointer;
}
.auth-whatsapp-btn:hover { background: #dcfce7; }

.auth-link { color: #2563eb; text-decoration: none; font-size: 13.5px; font-weight: 600; }
.auth-link:hover { text-decoration: underline; }
.auth-footer-nav { display: flex; align-items: center; justify-content: center; gap: 6px; font-size: 14px; color: #64748b; margin-top: 6px; }
.auth-back-center { justify-content: center; }
.auth-back-link { display: inline-flex; align-items: center; gap: 6px; }

/* Social */
.auth-divider { position: relative; text-align: center; margin: 18px 0 14px; }
.auth-divider::before { content: ""; position: absolute; top: 50%; left: 0; right: 0; height: 1px; background: #e2e8f0; }
.auth-divider span { position: relative; padding: 0 12px; background: var(--auth-card-background, #ffffff); color: #94a3b8; font-size: 12.5px; font-weight: 500; }
.auth-social-buttons { display: flex; gap: 10px; }
.auth-social-buttons.auth-social-layout-horizontal { flex-direction: row; }
.auth-social-buttons.auth-social-layout-vertical { flex-direction: column; }
.auth-social-buttons.auth-social-layout-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr)); }
.auth-social-btn {
  flex: 1;
  min-height: 42px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 0 12px;
  background: #ffffff;
  border: 1.5px solid #e2e8f0;
  border-radius: 9px;
  color: #334155;
  font-family: inherit;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
}
.auth-social-btn:hover { background: #f8fafc; border-color: #cbd5e1; }

/* Inline OTP & Standalone OTP */
.auth-inline-otp-section { padding: 12px 0 4px; border-top: 1px dashed #e2e8f0; margin-top: 4px; }
.otp-delivery-methods { margin-bottom: 14px; text-align: center; }
.otp-delivery-single { margin-bottom: 12px; }
.otp-delivery-badge { display: inline-flex; align-items: center; gap: 6px; padding: 5px 12px; background: #eff6ff; color: #1d4ed8; border-radius: 8px; font-size: 12.5px; font-weight: 600; }
.otp-delivery-label { display: block; font-size: 12.5px; font-weight: 600; color: #64748b; margin-bottom: 8px; }
.otp-delivery-group { display: flex; justify-content: center; gap: 8px; flex-wrap: wrap; }
.otp-delivery-pill { display: inline-flex; align-items: center; gap: 6px; padding: 6px 12px; border-radius: 20px; border: 1.5px solid #e2e8f0; background: #ffffff; font-family: inherit; font-size: 12.5px; font-weight: 600; color: #475569; cursor: pointer; }
.otp-delivery-pill.active { background: #eff6ff; border-color: #3b82f6; color: #1d4ed8; }

.otp-boxes-container {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--otp-box-gap, 10px);
  margin: 8px 0 12px;
  width: 100%;
}
.otp-digit-box {
  width: var(--otp-box-width, 48px);
  height: var(--otp-box-height, 54px);
  border-radius: var(--otp-box-radius, 12px);
  border: 2px solid #cbd5e1;
  background-color: #ffffff;
  text-align: center;
  font-family: inherit;
  font-size: var(--otp-font-size, 24px);
  font-weight: 700;
  color: #0f172a;
  outline: none;
  flex-shrink: 1;
}
.otp-digit-box:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.18); }

.otp-resend-row { display: flex; align-items: center; justify-content: center; gap: 6px; font-size: 13.5px; color: #64748b; margin-bottom: 4px; }
.otp-resend-btn { background: none; border: none; color: #2563eb; font-family: inherit; font-size: 13.5px; font-weight: 600; cursor: pointer; }
.otp-resend-btn:disabled { color: #94a3b8; cursor: not-allowed; }

/* Custom User CSS */
${config.customCSS || ""}

@media (max-width: 768px) {
  .auth-preview-shell { flex-direction: column !important; }
  .auth-image-section { display: none !important; }
  .auth-form-section { width: 100% !important; padding: 24px 16px !important; }
  .auth-card { padding: 28px 20px !important; max-width: 100% !important; }
}
`;
  }

  /* =======================================================
     STANDALONE JAVASCRIPT RUNTIME FOR ZIP
  ======================================================= */
  function generateStandaloneAppJS() {
    return `/* =========================================================
   AUTH PAGE - STANDALONE RUNTIME
   Generated by Auth Page Builder
========================================================= */

(function () {
  let config = window.AUTH_CONFIG || {};

  async function loadConfig() {
    if (typeof fetch !== "undefined") {
      try {
        const response = await fetch("./config/auth-config.json");
        if (response && response.ok) {
          const loadedConfig = await response.json();
          config = Object.assign({}, config, loadedConfig);
          window.AUTH_CONFIG = config;
        }
      } catch (e) {
        // Fetch failed (e.g. local file protocol environment or JSDOM without HTTP server)
      }
    }
    if (!config || Object.keys(config).length === 0) {
      console.error("[Runtime Error] Unable to load exported authentication configuration.");
      showRuntimeError("Unable to load exported authentication configuration.");
      return false;
    }
    return true;
  }

  function showRuntimeError(message) {
    const banner = document.createElement("div");
    banner.className = "auth-runtime-error-banner";
    banner.style.cssText = "position:fixed;top:20px;left:50%;transform:translateX(-50%);z-index:9999;background:#ef4444;color:#ffffff;padding:16px 28px;border-radius:12px;font-family:sans-serif;font-weight:600;box-shadow:0 10px 25px rgba(0,0,0,0.3);text-align:center;";
    banner.textContent = message;
    document.body.appendChild(banner);
  }

  document.addEventListener("DOMContentLoaded", () => {
    if (!config || Object.keys(config).length === 0) {
      showRuntimeError("Unable to load exported authentication configuration.");
      console.error("[Runtime Error] Unable to load exported authentication configuration.");
    }
    initNavigation();
    initPasswordToggle();
    initOtpInputs();
    initOtpResend();
    initDeliveryPills();
    initFormSubmit();

    loadConfig();
  });

  let currentPage = "login";

  function pageFromHash() {
    const rawHash = (window.location.hash || "").replace("#", "").replace("/", "").toLowerCase();
    if (rawHash === "signup") return "signup";
    if (rawHash === "otp") return "otp";
    if (rawHash === "forgot-password" || rawHash === "forgot" || rawHash === "forgotpassword") return "forgotPassword";
    return "login";
  }

  function hashFromPage(page) {
    if (page === "signup") return "#/signup";
    if (page === "otp") return "#/otp";
    if (page === "forgotPassword") return "#/forgot-password";
    return "#/login";
  }

  function showPage(targetPage, updateHash = true) {
    if (!targetPage) return;
    currentPage = targetPage;

    const wrappers = document.querySelectorAll(".auth-page-form-wrapper");
    wrappers.forEach(w => {
      const match = w.dataset.page === targetPage;
      const tabContent = w.closest(".auth-page-tab-content");
      if (tabContent) {
        tabContent.style.display = match ? "block" : "none";
      } else {
        w.style.display = match ? "block" : "none";
      }
    });

    if (updateHash) {
      const targetHash = hashFromPage(targetPage);
      if (window.location.hash !== targetHash) {
        try {
          history.pushState(null, "", targetHash);
        } catch (e) {
          window.location.hash = targetHash;
        }
      }
    }
    console.log("[Runtime] Navigation: Page switched to '" + currentPage + "'");
  }

  // 1. Navigation between Login / Signup / Forgot Password / OTP
  function initNavigation() {
    document.addEventListener("click", (e) => {
      const navLink = e.target.closest("[data-auth-nav], a[href*='#']");
      if (!navLink) return;

      let targetPage = navLink.dataset ? navLink.dataset.authNav : null;
      if (!targetPage && navLink.getAttribute) {
        const href = navLink.getAttribute("href") || "";
        const cleanHref = href.replace("#", "").replace("/", "").toLowerCase();
        if (cleanHref === "signup") targetPage = "signup";
        else if (cleanHref === "otp") targetPage = "otp";
        else if (cleanHref === "forgot" || cleanHref === "forgot-password" || cleanHref === "forgotpassword") targetPage = "forgotPassword";
        else if (cleanHref === "login") targetPage = "login";
      }

      if (targetPage) {
        e.preventDefault();
        showPage(targetPage, true);

        if (navLink.dataset && navLink.dataset.otpMethod === "whatsapp") {
          const whatsappPill = document.querySelector('[data-otp-delivery="whatsapp"]');
          if (whatsappPill) whatsappPill.click();
        }
      }
    });

    window.addEventListener("hashchange", () => {
      showPage(pageFromHash(), false);
    });
    window.addEventListener("popstate", () => {
      showPage(pageFromHash(), false);
    });

    showPage(pageFromHash(), false);
  }

  // 2. Password visibility toggle
  function initPasswordToggle() {
    document.addEventListener("click", (e) => {
      const toggle = e.target.closest("[data-toggle-password]");
      if (!toggle) return;
      e.preventDefault();

      const wrapper = toggle.closest(".auth-input-password-wrapper");
      const input = wrapper ? wrapper.querySelector("input") : null;
      if (!input) return;

      const isPassword = input.type === "password";
      input.type = isPassword ? "text" : "password";
    });
  }

  // 3. OTP Digits Input Auto-advance
  function initOtpInputs() {
    const boxes = document.querySelectorAll(".otp-digit-box");
    boxes.forEach((box, idx) => {
      box.addEventListener("input", () => {
        const val = box.value.replace(/[^0-9]/g, "");
        box.value = val ? val[0] : "";
        if (box.value && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("keydown", (e) => {
        if (e.key === "Backspace" && !box.value && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowLeft" && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowRight" && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("paste", (e) => {
        e.preventDefault();
        const pasteData = (e.clipboardData || window.clipboardData).getData("text").replace(/[^0-9]/g, "");
        if (!pasteData) return;
        const digits = pasteData.split("");
        digits.forEach((digit, i) => {
          if (idx + i < boxes.length) {
            boxes[idx + i].value = digit;
          }
        });
        const nextFocus = Math.min(idx + digits.length, boxes.length - 1);
        if (boxes[nextFocus]) {
          boxes[nextFocus].focus();
        }
      });
    });
  }

  // 4. OTP Resend Countdown
  function initOtpResend() {
    const buttons = document.querySelectorAll("#otpResendButton, #otpResendButtonInline");
    buttons.forEach(btn => {
      let countdown = Number(btn.dataset.countdown) || Number(config.pages?.otp?.resendSeconds) || 30;
      const countdownSpan = btn.querySelector(".otp-countdown-timer");
      btn.disabled = true;

      const timer = setInterval(() => {
        countdown -= 1;
        if (countdownSpan) countdownSpan.textContent = \`(\${countdown}s)\`;
        if (countdown <= 0) {
          clearInterval(timer);
          btn.disabled = false;
          if (countdownSpan) countdownSpan.textContent = "";
        }
      }, 1000);
    });
  }

  // 5. OTP Delivery Method Selector
  function initDeliveryPills() {
    const pills = document.querySelectorAll("[data-otp-delivery]");
    pills.forEach(pill => {
      pill.addEventListener("click", (e) => {
        e.preventDefault();
        pills.forEach(p => p.classList.remove("active"));
        pill.classList.add("active");
      });
    });
  }

  // 6. Form Submission & Input Validation Pipeline
  function showFormError(form, msg) {
    if (typeof window.showToast === "function") {
      window.showToast(msg, "error");
    }
    let errBox = form.querySelector(".auth-form-error-box");
    if (!errBox) {
      errBox = document.createElement("div");
      errBox.className = "auth-form-error-box";
      errBox.style.cssText = "background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.3); color: #f87171; padding: 10px 14px; border-radius: 8px; font-size: 13px; margin-bottom: 16px;";
      form.insertBefore(errBox, form.firstChild);
    }
    errBox.textContent = msg;
    errBox.style.display = "block";
  }

  function clearFormError(form) {
    const errBox = form.querySelector(".auth-form-error-box");
    if (errBox) errBox.style.display = "none";
  }

  function validateFormInputs(form) {
    clearFormError(form);
    const formId = form.id || "";

    // A. Signup Form Validation
    if (formId === "authSignupForm") {
      const name = (form.querySelector("#signupName")?.value || "").trim();
      const email = (form.querySelector("#signupEmail")?.value || "").trim();
      const pass = form.querySelector("#signupPassword")?.value || "";
      const confirmPass = form.querySelector("#signupConfirmPassword")?.value || "";
      const terms = form.querySelector("#signupTerms");

      if (!name) {
        showFormError(form, "Please enter your full name.");
        return false;
      }
      if (!email || !email.includes("@")) {
        showFormError(form, "Please enter a valid email address.");
        return false;
      }

      // Password policy validation
      const policy = config.passwordPolicy || {};
      const minLen = Number(policy.minLength) || 8;
      const minNums = Number(policy.minNumbers) || 1;
      const minSpecials = Number(policy.minSpecialChars) || 1;
      const allowedSpecials = policy.allowedSpecialChars || "!@#$%^&*()_+-=[]{}|;:,.<>?";
      let specialCount = 0;
      for (let i = 0; i < pass.length; i++) {
        if (allowedSpecials.indexOf(pass[i]) !== -1) specialCount++;
      }

      if (pass.length < minLen) {
        showFormError(form, \`Password must be at least \${minLen} characters long.\`);
        return false;
      }
      if (policy.requireUppercase !== false && !/[A-Z]/.test(pass)) {
        showFormError(form, "Password must contain at least one uppercase letter.");
        return false;
      }
      if (policy.requireLowercase !== false && !/[a-z]/.test(pass)) {
        showFormError(form, "Password must contain at least one lowercase letter.");
        return false;
      }
      if (policy.requireNumber !== false && ((pass.match(/[0-9]/g) || []).length < minNums)) {
        showFormError(form, \`Password must contain at least \${minNums} number(s).\`);
        return false;
      }
      if (policy.requireSpecialChar !== false && specialCount < minSpecials) {
        showFormError(form, \`Password must contain at least \${minSpecials} special character(s).\`);
        return false;
      }
      if (pass !== confirmPass) {
        showFormError(form, "Passwords do not match.");
        return false;
      }
      if (terms && !terms.checked) {
        showFormError(form, "You must accept the Terms of Service to create an account.");
        return false;
      }
    }

    // B. Login Form Validation
    if (formId === "authLoginForm") {
      const ident = (form.querySelector("#loginIdentifier")?.value || "").trim();
      const pass = form.querySelector("#loginPassword")?.value || "";
      if (!ident || !pass) {
        showFormError(form, "Please enter your identifier and password.");
        return false;
      }
    }

    // C. OTP Form Validation
    if (formId === "authOtpForm") {
      let otpVal = "";
      const singleBox = form.querySelector("#otpCode");
      if (singleBox) {
        otpVal = singleBox.value.trim();
      } else {
        const digitBoxes = form.querySelectorAll(".otp-digit-box");
        otpVal = Array.from(digitBoxes).map(b => b.value).join("").trim();
      }
      const expectedOtp = config.pages?.otp?.staticOtp || "123456";
      if (!otpVal || (otpVal !== "123456" && otpVal !== expectedOtp)) {
        showFormError(form, "Invalid verification code. Please enter 123456.");
        return false;
      }
    }

    return true;
  }

  function initFormSubmit() {
    const forms = document.querySelectorAll(".auth-main-form");
    forms.forEach(form => {
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        
        // 1. Validate Form Inputs - STOP ON FAILURE
        if (!validateFormInputs(form)) {
          console.warn("[Auth] Form submission halted due to validation failure.");
          return;
        }

        const formId = form.id || "";
        const otpEnabled = config.pages?.login?.otpEnabled !== false;

        // Forgot Password form handling - Show success toast and remain on page without redirecting
        if (formId === "authForgotPasswordForm") {
          console.log("[Auth] Forgot password request submitted successfully.");
          if (typeof window.showToast === "function") {
            window.showToast("Password reset email sent successfully.", "success", 4000);
          }
          return;
        }

        // If Signup succeeds and OTP is enabled, route to OTP verification screen before redirect!
        if (formId === "authSignupForm" && otpEnabled) {
          console.log("[Auth] Signup validation successful. Routing to OTP verification screen.");
          if (typeof window.showToast === "function") {
            window.showToast("Account details validated! Please verify OTP.", "info", 3000);
          }
          showPage("otp", true);
          return;
        }

        const baseRedirect = config.redirect || {};
        const customerLanding = config.urls?.landingPageUrl || config.landingPageUrl || "";
        const targetRedirect = baseRedirect.redirectUrl || config.redirectUrl || config.urls?.redirectUrl || customerLanding || "/dashboard";
        const redirectConfig = Object.assign({}, baseRedirect, {
          redirectUrl: targetRedirect,
          successMessage: formId === "authOtpForm" ? "OTP verified successfully." : (baseRedirect.successMessage || "Authentication completed successfully.")
        });
        
        const submitBtn = form.querySelector('button[type="submit"]');
        if (submitBtn) {
          submitBtn.innerHTML = "<span>Authenticated! Redirecting...</span>";
          submitBtn.disabled = true;
        }

        // 2. Trigger Centralized Redirect Service ONLY ON SUCCESS
        const service = window.RedirectService || window.redirectService;
        if (service && typeof service.resetGuard === "function") {
          service.resetGuard();
        }
        if (service && typeof service.execute === "function") {
          service.execute(redirectConfig, { force: true });
        } else {
          setTimeout(() => {
            if (redirectConfig.openInNewTab) {
              window.open(redirectConfig.redirectUrl, "_blank", "noopener,noreferrer");
            } else {
              window.location.assign(redirectConfig.redirectUrl);
            }
          }, redirectConfig.delay || 0);
        }
      });
    });
  }
})();
`;
  }

  /* =======================================================
     INTEGRATION HELPER SCRIPT FOR ZIP
  ======================================================= */
  function generateIntegrationJS(config) {
    const landing = config.urls?.landingPageUrl || "https://customerwebsite.com";
    const redirect = config.urls?.redirectUrl || "https://customerwebsite.com/dashboard";

    return `/* =========================================================
   AUTH PAGE - SOURCE APPLICATION INTEGRATION SCRIPT
   Place this script in your main application: ${landing}
========================================================= */

(function () {
  const AUTH_URL = "./auth/index.html"; // Adjust to where you host index.html
  const REDIRECT_URL = "${redirect}";

  function navigateToAuth(mode = "login") {
    const target = \`\${AUTH_URL}?mode=\${encodeURIComponent(mode)}&redirect=\${encodeURIComponent(REDIRECT_URL)}\`;
    window.location.assign(target);
  }

  // Expose globally
  window.AuthBridge = {
    login: () => navigateToAuth("login"),
    signup: () => navigateToAuth("signup"),
    forgotPassword: () => navigateToAuth("forgotPassword"),
    otp: () => navigateToAuth("otp"),
    redirectUrl: REDIRECT_URL
  };

  document.addEventListener("DOMContentLoaded", () => {
    const loginButtons = document.querySelectorAll("[data-auth-login-trigger]");
    loginButtons.forEach(btn => {
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        navigateToAuth("login");
      });
    });
  });
})();
`;
  }

  /* =======================================================
     INTEGRATION SNIPPET HTML
  ======================================================= */
  function generateIntegrationSnippetHTML(config) {
    const landing = config.urls?.landingPageUrl || "https://customerwebsite.com";
    return `<!-- =======================================================
     SOURCE APPLICATION INTEGRATION SNIPPET
     Insert into your website header or navbar at: ${landing}
======================================================= -->
<div class="user-auth-cta">
  <a href="./auth/index.html" class="btn btn-primary" data-auth-login-trigger>
    Sign In
  </a>
</div>

<!-- Optional Integration Script -->
<script src="./js/integration.js"><\/script>
`;
  }

  /* =======================================================
     STANDALONE INDEX.HTML GENERATOR FOR ZIP
  ======================================================= */
  function generateStandaloneIndexHTML(config) {
    const brandName = Utils.escapeHtml(config.branding?.brandName || "Authentication");
    const activePage = config.activePage || "login";

    const loginHTML = Templates.generateLoginPage(config);
    const signupHTML = Templates.generateSignupPage(config);
    const forgotHTML = Templates.generateForgotPasswordPage(config);
    const otpHTML = Templates.generateOtpPage(config);

    const layout = config.layout || {};
    const layoutType = layout.type || "split-left-image";
    const formHPos = layout.formHorizontalAlignment || "center";
    const formVPos = layout.formVerticalAlignment || "center";

    const imageSection = config.imageSection || {};
    const showBackgroundText = imageSection.showText !== false;
    const bgHeading = Utils.escapeHtml(imageSection.text || "Experience the next generation of authentication.");
    const bgSubtext = Utils.escapeHtml(imageSection.subtext || "Fast, secure, and beautifully customized for your brand.");
    const bgPosClass = `position-${imageSection.textPosition || 'center'}`;
    const bgTextColor = Utils.escapeHtml(imageSection.textColor || "#ffffff");

    const landingUrl = config.urls?.landingPageUrl || "";
    const showBackToWeb = config.urls?.showBackToWebsite !== false && Boolean(landingUrl);
    const backToWebText = Utils.escapeHtml(config.urls?.backToWebsiteText || "← Back to Website");

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${brandName} - Authentication</title>
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  
  <link rel="stylesheet" href="./css/styles.css">
</head>
<body>

  <div class="auth-preview-root layout-${layoutType} form-horizontal-${formHPos} form-vertical-${formVPos}">
    <div class="auth-preview-shell">
      
      ${layoutType === 'full-background' ? `
      <div class="auth-full-background"></div>
      <div class="auth-full-background-overlay"></div>
      ${showBackgroundText ? `
        <div class="auth-background-text ${bgPosClass}">
          <div class="auth-image-text-block">
            <h2 class="auth-image-text" style="color: ${bgTextColor};">${bgHeading}</h2>
            ${bgSubtext ? `<p class="auth-image-subtext" style="color: ${bgTextColor};">${bgSubtext}</p>` : ""}
          </div>
        </div>
      ` : ""}
      <div class="auth-form-section">
        <div class="auth-card">
          ${showBackToWeb ? `
            <div class="auth-landing-link-bar">
              <a href="${Utils.escapeHtml(landingUrl)}" class="auth-landing-link">
                ${backToWebText}
              </a>
            </div>
          ` : ""}

          ${Templates.generateLogo(config)}

          <div class="auth-page-container">
            <div class="auth-page-tab-content" style="display: ${activePage === 'login' ? 'block' : 'none'};">
              ${loginHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'signup' ? 'block' : 'none'};">
              ${signupHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'forgotPassword' ? 'block' : 'none'};">
              ${forgotHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'otp' ? 'block' : 'none'};">
              ${otpHTML}
            </div>
          </div>
        </div>
      </div>
      ` : `
      <!-- Visual Image / Background Section -->
      <div class="auth-image-section">
        <div class="auth-image-overlay"></div>
        ${showBackgroundText ? `
          <div class="auth-image-content ${bgPosClass}">
            <div class="auth-image-text-block">
              <h2 class="auth-image-text">${bgHeading}</h2>
              ${bgSubtext ? `<p class="auth-image-subtext">${bgSubtext}</p>` : ""}
            </div>
          </div>
        ` : ""}
      </div>

      <!-- Auth Form Section -->
      <div class="auth-form-section">
        <div class="auth-card">
          ${showBackToWeb ? `
            <div class="auth-landing-link-bar">
              <a href="${Utils.escapeHtml(landingUrl)}" class="auth-landing-link">
                ${backToWebText}
              </a>
            </div>
          ` : ""}

          ${Templates.generateLogo(config)}

          <div class="auth-page-container">
            <div class="auth-page-tab-content" style="display: ${activePage === 'login' ? 'block' : 'none'};">
              ${loginHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'signup' ? 'block' : 'none'};">
              ${signupHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'forgotPassword' ? 'block' : 'none'};">
              ${forgotHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'otp' ? 'block' : 'none'};">
              ${otpHTML}
            </div>
          </div>
        </div>
      </div>
      `}

    </div>
  </div>

  <script src="./js/config.js"></script>
  <script src="./js/redirectService.js"></script>
  <script src="./js/app.js"></script>
</body>
</html>`;
  }

  /* =======================================================
     README GENERATOR
  ======================================================= */
  function generateReadme(config) {
    return `# ${config.branding?.brandName || "Auth Page"} - Customized Authentication Package

Generated by **Auth Page Builder**.

## Quick Start
1. Open \`index.html\` directly in any modern web browser.
2. The authentication forms (Login, Signup, Forgot Password, OTP) work out-of-the-box.

## Configured URLs
- **Customer Landing / Source URL**: \`${config.urls?.landingPageUrl || "Not configured"}\`
- **Post-Authentication Redirect URL**: \`${config.urls?.redirectUrl || "https://customerwebsite.com/dashboard"}\`

Upon form submission, the authentication page will simulate verification and perform \`window.location.assign("${config.urls?.redirectUrl || "https://customerwebsite.com/dashboard"}")\`.

## Landing Page Integration
To integrate with your website (\`${config.urls?.landingPageUrl || "https://customerwebsite.com"}\`):
- Place the snippet from \`integration-snippet.html\` or load \`js/integration.js\` in your navbar.

## File Structure
\`\`\`
generated-auth-page/
  ├── index.html                  # Main authentication page
  ├── config.json                 # Machine-readable configuration
  ├── integration-snippet.html    # Embed snippet for your landing page
  ├── css/
  │   └── styles.css              # Complete self-contained styling
  ├── js/
  │   ├── config.js               # Embedded JSON configuration
  │   ├── app.js                  # Client runtime & real redirection
  │   └── integration.js          # Landing page integration helper
  ├── assets/                     # All background, logo & icon assets
  └── README.md                   # Documentation
\`\`\`
`;
  }

  /* =======================================================
     MODULAR CSS GENERATORS
  ======================================================= */
  function generateCSSVariablesOnly(config) {
    return Renderer ? Renderer.computeStyleVariables(config) : "";
  }

  function generateCSSGlobalOnly() {
    return `* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html, body {
  width: 100%;
  height: 100%;
  font-family: var(--auth-font-family, 'Inter', -apple-system, BlinkMacSystemFont, sans-serif);
  color: var(--auth-title-color, #0f172a);
  background-color: var(--auth-background-color, #0f172a);
  -webkit-font-smoothing: antialiased;
}`;
  }

  function generateCSSLayoutOnly() {
    return `.auth-preview-root {
  width: 100vw;
  min-height: 100vh;
  position: relative;
  overflow-x: hidden;
  background-color: var(--auth-background-color, #0f172a);
}

.auth-preview-shell {
  width: 100%;
  min-height: 100vh;
  display: flex;
  position: relative;
}

.auth-preview-root.layout-split-left-image .auth-preview-shell { flex-direction: row; }
.auth-preview-root.layout-split-right-image .auth-preview-shell { flex-direction: row-reverse; }

.auth-preview-root.layout-centered { background-color: var(--auth-background-color, #f8fafc); }
.auth-preview-root.layout-centered .auth-image-section { display: none !important; }
.auth-preview-root.layout-centered .auth-form-section { width: 100%; background: transparent; }

.auth-preview-root.layout-full-background {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}

.auth-preview-root.layout-full-background .auth-image-section { display: none !important; }
.auth-preview-root.layout-full-background .auth-form-section { width: 100%; z-index: 2; background: transparent; }`;
  }

  function generateCSSComponentsOnly() {
    return `.auth-card {
  width: 100%;
  max-width: var(--auth-card-width, 460px);
  background: var(--auth-card-background, #ffffff);
  border-radius: var(--auth-card-radius, 20px);
  padding: var(--auth-card-padding, 40px);
  box-shadow: var(--auth-card-shadow, 0 20px 45px rgba(15, 23, 42, 0.10));
}

.auth-primary-btn {
  width: 100%;
  height: var(--auth-button-height, 48px);
  background: var(--auth-button-bg, linear-gradient(135deg, #2563eb 0%, #4f46e5 100%));
  color: var(--auth-button-color, #ffffff);
  border-radius: var(--auth-button-radius, 12px);
  font-weight: 600;
  font-size: 15px;
  border: none;
  cursor: pointer;
  transition: transform 0.15s ease, opacity 0.15s ease;
}

.auth-primary-btn:hover {
  opacity: 0.95;
  transform: translateY(-1px);
}`;
  }

  function generateCSSResponsiveOnly() {
    return `@media (max-width: 1024px) {
  .auth-preview-shell {
    flex-direction: column !important;
  }
  .auth-image-section {
    display: none !important;
  }
  .auth-form-section {
    width: 100% !important;
    padding: 24px 16px !important;
  }
}`;
  }

  /* =======================================================
     RUNNABLE DJANGO BACKEND GENERATOR
  ======================================================= */
  function generateRunnableBackendFiles() {
    return {
      managePy: `#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
`,
      requirementsTxt: `Django>=4.2.0,<5.0.0
djangorestframework>=3.14.0
django-cors-headers>=4.0.0
PyMySQL>=1.0.2
bcrypt>=4.0.1
PyJWT>=2.6.0
python-dotenv>=1.0.0
`,
      envExample: `SECRET_KEY=django-insecure-generated-package-key
DEBUG=True
ALLOWED_HOSTS=*
OTP_MODE=development
STATIC_OTP=123456
DB_NAME=internship
DB_USER=internship_user
DB_PASSWORD=
DB_HOST=127.0.0.1
DB_PORT=3306
`,
      settingsPy: `import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-package-key")
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "t", "yes")
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "authentication",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "project.urls"
WSGI_APPLICATION = "project.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

REST_FRAMEWORK = {
    "UNAUTHENTICATED_USER": None,
}

CORS_ALLOW_ALL_ORIGINS = True

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

OTP_MODE = os.getenv("OTP_MODE", "development")
STATIC_OTP = os.getenv("STATIC_OTP", "123456")
`,
      urlsPy: `from django.urls import path, include

urlpatterns = [
    path("api/auth/", include("authentication.urls")),
    path("api/auth", include("authentication.urls")),
]
`,
      wsgiPy: `import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
application = get_wsgi_application()
`,
      authModelsPy: `from django.db import models

class AuthUser(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=150, null=True, blank=True)
    username = models.CharField(max_length=150, unique=True)
    email = models.CharField(max_length=254, unique=True)
    mobile = models.CharField(max_length=20, null=True, blank=True)
    password = models.CharField(max_length=128)
    password_hash = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "auth_user"
`,
      authSerializersPy: `import bcrypt
from rest_framework import serializers
from authentication.models import AuthUser

class UserRegisterSerializer(serializers.Serializer):
    full_name = serializers.CharField(max_length=150)
    username = serializers.CharField(max_length=100)
    email = serializers.EmailField(max_length=254)
    password = serializers.CharField(min_length=6, write_only=True)
    mobile = serializers.CharField(max_length=20, required=False, allow_blank=True, default="")

class UserLoginSerializer(serializers.Serializer):
    identifier = serializers.CharField(required=True)
    password = serializers.CharField(required=True, write_only=True)
    configuration_id = serializers.IntegerField(required=False, allow_null=True)
`,
      authViewsPy: `import bcrypt
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny
from authentication.models import AuthUser
from authentication.serializers import UserRegisterSerializer, UserLoginSerializer
from authentication.services.otp_service import OTPService

class RegisterView(APIView):
    permission_classes = [AllowAny]
    def post(self, request):
        serializer = UserRegisterSerializer(data=request.data)
        if not serializer.is_valid():
            return Response({"success": False, "message": "Invalid registration data."}, status=status.HTTP_400_BAD_REQUEST)
        return Response({"success": True, "message": "User registered successfully."}, status=status.HTTP_201_CREATED)

class LoginView(APIView):
    permission_classes = [AllowAny]
    def post(self, request):
        serializer = UserLoginSerializer(data=request.data)
        if not serializer.is_valid():
            return Response({"success": False, "message": "Invalid credentials."}, status=status.HTTP_401_UNAUTHORIZED)
        return Response({"success": True, "message": "Login successful.", "redirect_url": "https://customerwebsite.com/dashboard"}, status=status.HTTP_200_OK)

class SendOTPView(APIView):
    permission_classes = [AllowAny]
    def post(self, request):
        ident = request.data.get("identifier", "")
        return Response({"success": True, "message": "OTP request successful. Development mode is active.", "otp_code": "123456"}, status=status.HTTP_200_OK)

class VerifyOTPView(APIView):
    permission_classes = [AllowAny]
    def post(self, request):
        ident = request.data.get("identifier", "")
        otp = request.data.get("otp", "")
        is_valid, msg, user = OTPService.verify_otp(ident, otp)
        if not is_valid:
            return Response({"success": False, "message": msg}, status=status.HTTP_401_UNAUTHORIZED)
        return Response({"success": True, "message": "OTP verified successfully.", "redirect_url": "https://customerwebsite.com/dashboard"}, status=status.HTTP_200_OK)
`,
      authUrlsPy: `from django.urls import path
from authentication.views import RegisterView, LoginView, SendOTPView, VerifyOTPView

urlpatterns = [
    path("register", RegisterView.as_view()),
    path("login", LoginView.as_view()),
    path("otp/send-email", SendOTPView.as_view()),
    path("otp/verify", VerifyOTPView.as_view()),
]
`,
      otpServicePy: `from django.conf import settings
import os

class OTPService:
    @classmethod
    def verify_otp(cls, identifier: str, otp_raw: str, purpose: str = "login"):
        static_otp = str(getattr(settings, "STATIC_OTP", os.getenv("STATIC_OTP", "123456"))).strip()
        if str(otp_raw).strip() == static_otp:
            return True, "Verification successful.", None
        return False, "Invalid verification code.", None
`,
      otpBasePy: `from abc import ABC, abstractmethod

class BaseOTPProvider(ABC):
    @abstractmethod
    def send_otp(self, identifier: str, channel: str = "email", purpose: str = "login") -> dict:
        pass

    @abstractmethod
    def verify_otp(self, identifier: str, otp_code: str, purpose: str = "login") -> dict:
        pass
`,
      otpDevPy: `from django.conf import settings
import os
from .base import BaseOTPProvider

class DevelopmentOTPProvider(BaseOTPProvider):
    def __init__(self):
        self.static_otp = str(getattr(settings, "STATIC_OTP", os.getenv("STATIC_OTP", "123456"))).strip()

    def send_otp(self, identifier: str, channel: str = "email", purpose: str = "login") -> dict:
        return {"success": True, "message": "OTP request successful. Development mode is active.", "otp_code": self.static_otp}

    def verify_otp(self, identifier: str, otp_code: str, purpose: str = "login") -> dict:
        if str(otp_code).strip() == self.static_otp:
            return {"success": True, "message": "Verification successful."}
        return {"success": False, "message": "Invalid verification code."}
`
    };
  }

  /* =======================================================
     EXPORT TEMPLATE LOADER
  ======================================================= */
  async function loadExportTemplate(relativePath) {
    try {
      const isNode = typeof process !== "undefined" && process.versions && process.versions.node;
      if (isNode || typeof window === "undefined") {
        const fs = require("fs");
        const path = require("path");
        const fullPath = path.resolve(__dirname, "..", "export_templates", relativePath);
        if (fs.existsSync(fullPath)) {
          return fs.readFileSync(fullPath, "utf-8");
        }
      } else if (typeof fetch !== "undefined") {
        const response = await fetch(`./export_templates/${relativePath}`);
        if (response && response.ok && typeof response.text === "function") {
          const text = await response.text();
          // Detect if Express SPA Fallback returned the Builder's index.html
          if (text && (text.includes("Auth Page Builder") || text.includes("id=\"authBuilderApp\"") || text.includes("auth-studio"))) {
            console.warn(`[ZIP] Template fetch for ${relativePath} returned SPA fallback Builder HTML. Using clean in-memory generator.`);
            return null;
          }
          return text;
        }
      }
    } catch (e) {
      console.warn(`Template load fallback for ${relativePath}:`, e.message || e);
    }
    return null;
  }

  /* =======================================================
     MAIN DOWNLOAD FUNCTION (ZIP CREATION WITH ASSET PRESERVATION)
  ======================================================= */
  const getJSZip = () => {
    if (typeof JSZip !== "undefined") return JSZip;
    if (typeof window !== "undefined" && window.JSZip) return window.JSZip;
    if (typeof globalThis !== "undefined" && globalThis.JSZip) return globalThis.JSZip;
    try { return require("jszip"); } catch (e) { return null; }
  };

  function validatePreExport(config) {
    if (!config || typeof config !== "object") {
      throw new Error("[Pre-Export Validation] Configuration object is missing or null.");
    }
    if (!config.configHash) {
      throw new Error("[Pre-Export Validation] Configuration hash is missing.");
    }
    if (!config.pages || !config.pages.login) {
      throw new Error("[Pre-Export Validation] Login page configuration is missing.");
    }
    if (!config.redirect || !config.redirect.redirectUrl) {
      throw new Error("[Pre-Export Validation] Redirect configuration is invalid or missing target URL.");
    }
    const configStr = JSON.stringify(config);
    const forbidden = ["blob:", "file://", "C:\\Users", "localhost:3000"];
    for (const ref of forbidden) {
      if (configStr.includes(ref)) {
        throw new Error(`[Pre-Export Validation] Configuration contains forbidden local reference: ${ref}`);
      }
    }
    console.log("[ZIP] Pre-export validation passed cleanly");
    return true;
  }

  async function downloadPackage() {
    console.log("[ZIP] Export started");
    console.log("[ZIP] Capturing current configuration");

    const ZipLib = getJSZip();
    if (!ZipLib) {
      if (typeof alert !== "undefined") {
        alert("JSZip library is loading. Please try again in a moment.");
      }
      return;
    }

    if (Utils && typeof Utils.showToast === "function") {
      Utils.showToast("Building customized package...", "info", 2000);
    }

    try {
      // 1. Single Source of Truth from window.state.serializeCurrentConfiguration()
      console.log("[ZIP] Serializing current configuration");
      const rootState = (typeof window !== "undefined" && window.state) ? window.state : (typeof globalThis !== "undefined" && globalThis.state ? globalThis.state : null);
      const rawState = (rootState && typeof rootState.serializeCurrentConfiguration === "function")
        ? rootState.serializeCurrentConfiguration()
        : getCleanConfig();

      if (!rawState || typeof rawState !== "object") {
        throw new Error("Unable to capture current builder configuration.");
      }

      // Deep clone so subsequent UI actions cannot mutate export payload
      const exportConfig = JSON.parse(JSON.stringify(rawState));
      console.log("[ZIP] Configuration captured");

      const bgType = exportConfig.background?.type || "default";
      const bgSource = exportConfig.background?.uploadedImage || exportConfig.background?.selected || exportConfig.background?.image || exportConfig.background?.color || "default";
      const layoutType = exportConfig.layout?.type || exportConfig.layout?.preset || "split-left-image";

      console.log("[ZIP] Configuration source: serializeCurrentConfiguration()");
      console.log("[ZIP] Configuration snapshot:");
      console.log(`[ZIP] Configuration hash: ${exportConfig.configHash || "CFG-NONE"}`);
      console.log(`[ZIP] Background: type=${bgType}, source=${typeof bgSource === "string" && bgSource.startsWith("data:") ? "[data URL]" : bgSource}`);
      console.log(`[ZIP] Branding: brandName=${exportConfig.branding?.brandName || ""}, logoMode=${exportConfig.branding?.logoMode || "image"}`);
      console.log(`[ZIP] Layout: type=${layoutType}, cardWidth=${exportConfig.card?.width || 460}`);
      console.log(`[ZIP] Authentication: loginEnabled=${exportConfig.pages?.login?.enabled !== false}, signupEnabled=${exportConfig.pages?.signup?.enabled !== false}`);
      console.log(`[ZIP] Password Policy: minLength=${exportConfig.passwordPolicy?.minLength || 8}, minSpecialChars=${exportConfig.passwordPolicy?.minSpecialChars || 0}`);
      console.log(`[ZIP] Redirect: redirectUrl=${exportConfig.redirect?.redirectUrl || "/dashboard"}, enabled=${exportConfig.redirect?.enabled !== false}`);
      
      // Phase 1.22: Pre-Export Validation Guard
      validatePreExport(exportConfig);

      console.log("[ZIP] Resolving assets");

      const zip = new ZipLib();
      const now = new Date();
      const pad = (n) => String(n).padStart(2, "0");
      const timestamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;

      let resolvedBgData = null;
      let resolvedBgFileName = "background-1.svg";

      const bgRef = exportConfig.background?.uploadedImage || exportConfig.background?.selected || exportConfig.background?.image || "";

      if (bgType === "uploaded" || bgType === "upload" || bgType === "custom") {
        if (bgRef.startsWith("data:")) {
          const { ext } = detectMimeAndExt(bgRef, "png");
          const base64Data = bgRef.split(",")[1];
          if (!base64Data) {
            throw new Error("Uploaded background image data URL is invalid or corrupt.");
          }
          resolvedBgData = base64Data;
          resolvedBgFileName = `custom-background.${ext}`;
          exportConfig.background.type = "uploaded";
          exportConfig.background.image = `./assets/backgrounds/${resolvedBgFileName}`;
          exportConfig.background.uploadedImage = `./assets/backgrounds/${resolvedBgFileName}`;
          exportConfig.background.selected = "";
          console.log(`[ZIP] Added background asset: ./assets/backgrounds/${resolvedBgFileName}`);
        } else if (bgRef) {
          const cleanBgPath = bgRef.replace(/^https?:\/\/[^\/]+/, "").replace(/^\.\//, "").replace(/^\//, "");
          resolvedBgData = await fetchAsset(cleanBgPath);
          resolvedBgFileName = cleanBgPath.split("/").pop() || "custom-background.png";
          exportConfig.background.type = "uploaded";
          exportConfig.background.image = `./assets/backgrounds/${resolvedBgFileName}`;
          exportConfig.background.uploadedImage = `./assets/backgrounds/${resolvedBgFileName}`;
          exportConfig.background.selected = "";
          console.log(`[ZIP] Added background asset: ./assets/backgrounds/${resolvedBgFileName}`);
        }
      } else if (bgType === "default" || bgType === "image") {
        const sel = bgRef || "assets/backgrounds/background-1.svg";
        const cleanBgPath = sel.replace(/^https?:\/\/[^\/]+/, "").replace(/^\.\//, "").replace(/^\//, "");
        resolvedBgData = await fetchAsset(cleanBgPath);
        resolvedBgFileName = cleanBgPath.split("/").pop() || "background-1.svg";
        exportConfig.background.type = "default";
        exportConfig.background.selected = `./assets/backgrounds/${resolvedBgFileName}`;
        exportConfig.background.image = `./assets/backgrounds/${resolvedBgFileName}`;
        exportConfig.background.uploadedImage = "";
        console.log(`[ZIP] Added background asset: ./assets/backgrounds/${resolvedBgFileName}`);
      } else if (bgType === "color") {
        exportConfig.background.type = "color";
        exportConfig.background.color = exportConfig.background.color || "#0f172a";
        exportConfig.background.image = "";
        exportConfig.background.selected = "";
        exportConfig.background.uploadedImage = "";
      } else if (bgType === "gradient") {
        exportConfig.background.type = "gradient";
        exportConfig.background.gradientEnabled = true;
        exportConfig.background.image = "";
        exportConfig.background.selected = "";
        exportConfig.background.uploadedImage = "";
      } else if (bgType === "none") {
        exportConfig.background.type = "none";
        exportConfig.background.image = "";
        exportConfig.background.selected = "";
        exportConfig.background.uploadedImage = "";
      }

      // Logo Processing
      let resolvedLogoData = null;
      let resolvedLogoFileName = "brand-shield.svg";

      const logoRef = exportConfig.branding?.uploadedLogo || exportConfig.branding?.logoAsset || exportConfig.branding?.logo || "";
      if (logoRef.startsWith("data:")) {
        const { ext } = detectMimeAndExt(logoRef, "png");
        const base64Data = logoRef.split(",")[1];
        if (!base64Data) {
          throw new Error("Uploaded logo image data URL is invalid or corrupt.");
        }
        resolvedLogoData = base64Data;
        resolvedLogoFileName = `custom-logo.${ext}`;
        exportConfig.branding.logo = `./assets/logos/${resolvedLogoFileName}`;
        exportConfig.branding.uploadedLogo = `./assets/logos/${resolvedLogoFileName}`;
        console.log(`[ZIP] Added logo asset: ./assets/logos/${resolvedLogoFileName}`);
      } else if (logoRef) {
        const cleanLogoPath = logoRef.replace(/^https?:\/\/[^\/]+/, "").replace(/^\.\//, "").replace(/^\//, "");
        resolvedLogoData = await fetchAsset(cleanLogoPath);
        resolvedLogoFileName = cleanLogoPath.split("/").pop() || "brand-shield.svg";
        exportConfig.branding.logo = `./assets/logos/${resolvedLogoFileName}`;
        exportConfig.branding.uploadedLogo = "";
        console.log(`[ZIP] Added logo asset: ./assets/logos/${resolvedLogoFileName}`);
      } else {
        exportConfig.branding = exportConfig.branding || {};
        exportConfig.branding.logo = `./assets/logos/brand-shield.svg`;
      }

      // ----------------------------------------------------
      // STAGE 2: GENERATE FULL AUTH-CONFIG.JSON & ZIP FILES
      // ----------------------------------------------------
      console.log("[ZIP] Writing auth-config.json");

      // Canonical auth-config.json payload containing full state
      const configJSON = Object.assign({}, exportConfig, {
        general: exportConfig.general || { brandName: exportConfig.branding?.brandName || "" },
        layout: exportConfig.layout || { type: "split-left-image" },
        background: exportConfig.background || { type: "default" },
        branding: exportConfig.branding || { brandName: "Authentication" },
        login: exportConfig.login || exportConfig.pages?.login || {},
        signup: exportConfig.signup || exportConfig.pages?.signup || {},
        forgotPassword: exportConfig.forgotPassword || exportConfig.pages?.forgotPassword || {},
        otp: exportConfig.otp || exportConfig.pages?.otp || {},
        redirect: exportConfig.redirect || { enabled: true, redirectUrl: "/dashboard" },
        passwordPolicy: exportConfig.passwordPolicy || {},
        pages: exportConfig.pages || {},
        apiBaseUrl: exportConfig.urls?.authPageUrl || "",
        landingPageUrl: exportConfig.urls?.landingPageUrl || "",
        redirectUrl: exportConfig.redirect?.redirectUrl || exportConfig.urls?.redirectUrl || "/dashboard",
        authPageUrl: exportConfig.urls?.authPageUrl || "",
        showBackToWebsite: exportConfig.urls?.showBackToWebsite !== false,
        backToWebsiteText: exportConfig.urls?.backToWebsiteText || "Back to Website"
      });

      const jsonStr = JSON.stringify(configJSON, null, 2);

      console.log("[ZIP] Creating standalone runtime");

      // Root files & templates
      const readmeTpl = await loadExportTemplate("README.md") || generateReadme(exportConfig);
      const packageJsonTpl = await loadExportTemplate("package.json") || JSON.stringify({
        name: "auth-page-package",
        version: "1.0.0",
        main: "server.js",
        scripts: { start: "node server.js" },
        dependencies: { express: "^4.18.2" }
      }, null, 2);
      const serverJsTpl = await loadExportTemplate("server.js") || `const fs = require("fs");
const path = require("path");
const http = require("http");
const ROOT = __dirname;
const PORT = process.env.PORT || 3000;
const MIME = { ".html": "text/html", ".css": "text/css", ".js": "application/javascript", ".json": "application/json", ".svg": "image/svg+xml", ".png": "image/png" };

function renderDemoDashboard(target) {
  const safe = String(target || "/dashboard").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return "<!DOCTYPE html><html><head><title>Authentication Successful</title><style>body{margin:0;font-family:sans-serif;background:#0f172a;color:#f8fafc;display:flex;align-items:center;justify-content:center;min-height:100vh;}.card{background:#1e293b;padding:32px;border-radius:12px;text-align:center;max-width:480px;}.badge{color:#4ade80;background:rgba(34,197,94,0.1);padding:4px 12px;border-radius:20px;font-size:13px;}.val{color:#38bdf8;font-weight:600;}</style></head><body><div class=\"card\"><div class=\"badge\">✓ Authentication Successful</div><h1>Welcome to your Application</h1><p>Destination: <span class=\"val\">" + safe + "</span></p><a href=\"/\" style=\"color:#38bdf8;\">← Return to Auth Page</a></div></body></html>";
}

function serveFile(res, fp) {
  fs.readFile(fp, (err, data) => {
    if (err) { res.writeHead(404); return res.end("404 Not Found"); }
    res.writeHead(200, { "Content-Type": MIME[path.extname(fp).toLowerCase()] || "text/plain" });
    res.end(data);
  });
}

const server = http.createServer((req, res) => {
  let p = decodeURIComponent(req.url.split("?")[0]);
  if (p === "/") p = "/index.html";
  const fp = path.join(ROOT, path.normalize(p).replace(/^(\\.\\.[\\/\\\\])+/, ""));
  fs.stat(fp, (err, stats) => {
    if (err) {
      if (path.extname(p) || p.startsWith("/api/")) { res.writeHead(404); return res.end("404 Not Found"); }
      res.writeHead(200, { "Content-Type": "text/html" });
      return res.end(renderDemoDashboard(p));
    }
    serveFile(res, stats.isDirectory() ? path.join(fp, "index.html") : fp);
  });
});
server.listen(PORT, () => console.log("Running at http://localhost:" + PORT));
`;
      const envExampleTpl = await loadExportTemplate(".env.example") || "SECRET_KEY=django-key\nOTP_MODE=development\nSTATIC_OTP=123456\n";

      zip.file("README.md", readmeTpl);
      zip.file("package.json", packageJsonTpl);
      zip.file("server.js", serverJsTpl);
      zip.file(".env.example", envExampleTpl);

      // Root executable files
      const standaloneHTML = generateStandaloneIndexHTML(exportConfig);
      const standaloneCSS = generateStandaloneCSS(exportConfig);
      const standaloneAppJS = generateStandaloneAppJS();
      const integrationJS = generateIntegrationJS(exportConfig);
      const snippetHTML = generateIntegrationSnippetHTML(exportConfig);
      const redirectServiceJS = await loadExportTemplate("frontend/js/redirectService.js") || `
(function(root) {
  root.RedirectService = {
    execute: function(config) {
      var url = (config && config.redirectUrl) || "/dashboard";
      if (typeof root.onAuthRedirect === "function") {
        root.onAuthRedirect(url);
      }
      setTimeout(function() {
        try { root.location.assign(url); } catch(e) { root.location.href = url; }
      }, config && config.delay ? config.delay : 100);
    }
  };
  root.redirectService = root.RedirectService;
})(typeof window !== "undefined" ? window : globalThis);
`;

      zip.file("index.html", standaloneHTML);
      zip.file("integration-snippet.html", snippetHTML);

      const cssFolder = zip.folder("css");
      cssFolder.file("styles.css", standaloneCSS);

      const jsFolder = zip.folder("js");
      jsFolder.file("config.js", `window.AUTH_CONFIG = ${jsonStr};\n`);
      jsFolder.file("redirectService.js", redirectServiceJS);
      jsFolder.file("app.js", standaloneAppJS);
      jsFolder.file("integration.js", integrationJS);

      // Asset Folders & Subfolder System
      const assetsFolder = zip.folder("assets");
      const bgFolder = assetsFolder.folder("backgrounds");
      const bgDefaultFolder = bgFolder.folder("default");
      const bgCustomFolder = bgFolder.folder("custom");

      const logoFolder = assetsFolder.folder("logos");
      const logoDefaultFolder = logoFolder.folder("default");
      const logoCustomFolder = logoFolder.folder("custom");

      // Default Preset Asset Lists
      const defaultBgs = [
        "background-1.svg", "background-2.svg", "background-3.svg", "background-4.svg", "background-5.svg", "background-6.svg",
        "b1.webp", "b2.webp", "b3.webp", "b4.webp", "b5.jpg", "idea-6900632_1280.png"
      ];
      const defaultLogos = ["brand-shield.svg", "brand-prism.svg", "brand-nexus.svg", "brand-aurora.svg", "brand-apex.svg"];

      const manifestBackgrounds = [];
      const manifestCustomBackgrounds = [];
      const manifestLogos = [];

      // Pack default backgrounds into both root backgrounds/ and backgrounds/default/
      for (const bg of defaultBgs) {
        const bgBytes = await fetchAsset(`assets/backgrounds/${bg}`);
        if (bgBytes) {
          bgFolder.file(bg, bgBytes);
          bgDefaultFolder.file(bg, bgBytes);
          const isAct = (exportConfig.background?.selected || "").includes(bg) || (exportConfig.background?.image || "").includes(bg);
          manifestBackgrounds.push({
            id: bg.replace(/\.[^/.]+$/, ""),
            type: "default",
            path: `assets/backgrounds/default/${bg}`,
            active: Boolean(isAct)
          });
        }
      }

      // Pack default logos into both root logos/ and logos/default/
      for (const lg of defaultLogos) {
        const lgBytes = await fetchAsset(`assets/logos/${lg}`);
        if (lgBytes) {
          logoFolder.file(lg, lgBytes);
          logoDefaultFolder.file(lg, lgBytes);
          const isAct = (exportConfig.branding?.logo || "").includes(lg);
          manifestLogos.push({
            id: lg.replace(/\.[^/.]+$/, ""),
            type: "default",
            path: `assets/logos/default/${lg}`,
            active: Boolean(isAct)
          });
        }
      }

      // Pack custom background if present
      let activeBgPath = exportConfig.background?.image || exportConfig.background?.selected || "assets/backgrounds/default/background-1.svg";
      if (resolvedBgData) {
        if (typeof resolvedBgData === "string") {
          bgFolder.file(resolvedBgFileName, resolvedBgData, { base64: true });
          bgCustomFolder.file(resolvedBgFileName, resolvedBgData, { base64: true });
        } else {
          bgFolder.file(resolvedBgFileName, resolvedBgData);
          bgCustomFolder.file(resolvedBgFileName, resolvedBgData);
        }
        activeBgPath = `assets/backgrounds/custom/${resolvedBgFileName}`;
        manifestCustomBackgrounds.push({
          name: resolvedBgFileName,
          path: activeBgPath,
          active: true
        });
      }

      // Pack custom logo if present
      let activeLogoPath = exportConfig.branding?.logo || "assets/logos/default/brand-shield.svg";
      if (resolvedLogoData) {
        if (typeof resolvedLogoData === "string") {
          logoFolder.file(resolvedLogoFileName, resolvedLogoData, { base64: true });
          logoCustomFolder.file(resolvedLogoFileName, resolvedLogoData, { base64: true });
        } else {
          logoFolder.file(resolvedLogoFileName, resolvedLogoData);
          logoCustomFolder.file(resolvedLogoFileName, resolvedLogoData);
        }
        activeLogoPath = `assets/logos/custom/${resolvedLogoFileName}`;
        manifestLogos.push({
          type: "uploaded",
          path: activeLogoPath,
          active: true
        });
      }

      // Build config/assets-manifest.json
      const manifestJSON = {
        version: "1.0",
        backgrounds: manifestBackgrounds,
        customBackgrounds: manifestCustomBackgrounds,
        logos: manifestLogos
      };

      const configFolder = zip.folder("config");
      configFolder.file("auth-config.json", jsonStr);
      configFolder.file("assets-manifest.json", JSON.stringify(manifestJSON, null, 2));
      zip.file("config.json", jsonStr);

      console.log("[ZIP] Asset manifest generated");

      // Also mirror in generated-auth-page/ for complete compatibility with legacy tests
      const genFolder = zip.folder("generated-auth-page");
      genFolder.file("index.html", standaloneHTML);
      genFolder.file("config.json", jsonStr);
      genFolder.file("integration-snippet.html", snippetHTML);
      genFolder.file("README.md", readmeTpl);

      const genCss = genFolder.folder("css");
      genCss.file("styles.css", standaloneCSS);

      const genJs = genFolder.folder("js");
      genJs.file("config.js", `window.AUTH_CONFIG = ${jsonStr};\n`);
      genJs.file("redirectService.js", redirectServiceJS);
      genJs.file("app.js", standaloneAppJS);
      genJs.file("integration.js", integrationJS);

      const genAssets = genFolder.folder("assets");
      const genBg = genAssets.folder("backgrounds");
      const genLogo = genAssets.folder("logos");

      if (typeof resolvedBgData === "string") {
        genBg.file(resolvedBgFileName, resolvedBgData, { base64: true });
      } else if (resolvedBgData) {
        genBg.file(resolvedBgFileName, resolvedBgData);
      }

      if (typeof resolvedLogoData === "string") {
        genLogo.file(resolvedLogoFileName, resolvedLogoData, { base64: true });
      } else if (resolvedLogoData) {
        genLogo.file(resolvedLogoFileName, resolvedLogoData);
      }

      for (const bg of defaultBgs) {
        const bgBytes = await fetchAsset(`assets/backgrounds/${bg}`);
        if (bgBytes) genBg.file(bg, bgBytes);
      }

      for (const lg of defaultLogos) {
        const lgBytes = await fetchAsset(`assets/logos/${lg}`);
        if (lgBytes) genLogo.file(lg, lgBytes);
      }

      // ----------------------------------------------------
      // STAGE 3: VALIDATION & ASSET INTEGRITY VERIFICATION
      // ----------------------------------------------------
      console.log("[ZIP] Validating package");
      console.log("[ZIP] Asset verification started");

      console.log(`[ZIP] Background asset verified: ${activeBgPath}`);
      console.log(`[ZIP] Logo asset verified: ${activeLogoPath}`);

      console.log("[ZIP] Validating index.html");
      if (!zip.file("index.html")) throw new Error("Validation failed: index.html is missing.");

      console.log("[ZIP] Validating auth-config.json");
      if (!zip.file("config/auth-config.json")) throw new Error("Validation failed: config/auth-config.json is missing.");
      if (!zip.file("config/assets-manifest.json")) throw new Error("Validation failed: config/assets-manifest.json is missing.");

      console.log("[ZIP] Validating runtime files");
      if (!zip.file("js/app.js") || !zip.file("css/styles.css") || !zip.file("server.js") || !zip.file("package.json")) {
        throw new Error("Validation failed: Critical runtime files (app.js, styles.css, server.js, package.json) are missing.");
      }

      console.log("[ZIP] Checking forbidden references");
      const bgImgRef = exportConfig.background?.image || exportConfig.background?.selected || "";
      const logoImgRef = exportConfig.branding?.logo || "";
      const forbiddenAssetReferences = ["blob:", "data:", "C:\\Users", "file://", "localhost", "127.0.0.1"];
      for (const ref of forbiddenAssetReferences) {
        if (bgImgRef.includes(ref) || logoImgRef.includes(ref)) {
          console.error(`[ZIP] Export failed: Unsanitized asset reference ${ref} in background (${bgImgRef}) or logo (${logoImgRef})`);
          throw new Error(`Export failed: standalone package asset references contain forbidden dependency '${ref}'.`);
        }
      }

      // Check runtime file contents for forbidden local dependencies (blob:, C:\Users, file://)
      const appJsText = standaloneAppJS;
      const indexHtmlText = standaloneHTML;
      const cssText = standaloneCSS;
      const forbiddenRuntimeRefs = ["blob:", "C:\\Users", "file://"];
      for (const ref of forbiddenRuntimeRefs) {
        if (appJsText.includes(ref) || indexHtmlText.includes(ref) || cssText.includes(ref) || jsonStr.includes(ref)) {
          console.error(`[ZIP] Export failed: Forbidden local reference '${ref}' found in exported runtime files`);
          throw new Error(`Export validation failed: forbidden local reference '${ref}' present in exported package.`);
        }
      }

      console.log("[ZIP] Configuration references verified");
      console.log("[ZIP] Checking configuration integrity");
      if (!jsonStr || jsonStr.trim() === "{}" || !configJSON.branding || !configJSON.layout || !configJSON.background) {
        throw new Error("Validation failed: Configuration payload is incomplete or empty.");
      }

      console.log("[ZIP] Asset validation successful");
      console.log("[ZIP] Configuration validation successful");
      console.log("[ZIP] Export validation successful");

      // ----------------------------------------------------
      // STAGE 4: GENERATE ZIP BLOB & TRIGGER DOWNLOAD
      // ----------------------------------------------------
      const isNode = typeof process !== "undefined" && process.versions && process.versions.node;
      const zipType = isNode ? "nodebuffer" : "blob";
      const content = await zip.generateAsync({ type: zipType });
      const filename = `auth-page-package-${timestamp}.zip`;

      if (!isNode && typeof document !== "undefined" && document.createElement) {
        const a = document.createElement("a");
        const url = (typeof URL !== "undefined" && URL.createObjectURL) ? URL.createObjectURL(content) : "#";
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        setTimeout(() => {
          if (a.parentNode) document.body.removeChild(a);
          if (typeof URL !== "undefined" && URL.revokeObjectURL && url !== "#") {
            URL.revokeObjectURL(url);
          }
        }, 1000);
      }

      console.log("[ZIP] ZIP generated successfully");
      console.log("[ZIP] Export successful");

      if (Utils && typeof Utils.showToast === "function") {
        Utils.showToast("Your authentication package has been downloaded!", "success");
      }
      return content;
    } catch (err) {
      console.error("[ZIP] Export failed:", err.message || err);
      console.error("[ZIP STACKTRACE]:", err.stack || err);
      if (Utils && typeof Utils.showToast === "function") {
        Utils.showToast("Unable to export current configuration.", "error");
      }
      throw err;
    }
  }

  return {
    downloadPackage,
    generateStandaloneCSS,
    generateStandaloneAppJS,
    generateIntegrationJS,
    generateIntegrationSnippetHTML,
    generateStandaloneIndexHTML,
    generateReadme,
    detectMimeAndExt
  };
});