/* =========================================================
   AUTH PAGE BUILDER - DOWNLOAD PACKAGE GENERATOR
   File: js/download.js
========================================================= */

(function (root, factory) {
  if (typeof module !== "undefined" && module.exports) {
    const templates = require("./templates.js");
    const renderer = require("./renderer.js");
    const utils = require("./utils.js");
    module.exports = factory(templates, renderer, utils);
  } else {
    const downloadManager = factory(root.Templates, root.AuthPageRenderer, root.Utils);
    root.DownloadManager = downloadManager;
    root.downloadPackage = downloadManager.downloadPackage;
  }
})(typeof window !== "undefined" ? window : globalThis, function (Templates, Renderer, Utils) {

  function getCleanConfig() {
    const state = window.state ? window.state.getState() : (window.config || {});
    return JSON.parse(JSON.stringify(state));
  }

  /* =======================================================
     FETCH LOCAL ASSET AS ARRAYBUFFER
  ======================================================= */
  async function fetchAsset(url) {
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return await response.arrayBuffer();
    } catch (e) {
      console.warn(`Could not fetch asset ${url}:`, e);
      return null;
    }
  }

  /* =======================================================
     STANDALONE CSS GENERATOR
  ======================================================= */
  function generateStandaloneCSS(config) {
    const dynamicVars = Renderer ? Renderer.computeStyleVariables(config) : "";
    
    return `/* =========================================================
   AUTH PAGE - STANDALONE STYLESHEET
   Generated by Auth Page Builder
========================================================= */

${dynamicVars}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html, body {
  width: 100%;
  height: 100%;
  font-family: var(--auth-font-family, 'Inter', -apple-system, BlinkMacSystemFont, sans-serif);
  color: var(--auth-title-color, #0f172a);
  background-color: var(--auth-background-color, #0f172a);
}

.auth-preview-root {
  width: 100vw;
  min-height: 100vh;
  position: relative;
  overflow-x: hidden;
  background-color: var(--auth-background-color, #0f172a);
}

.auth-preview-shell {
  width: 100%;
  min-height: 100vh;
  display: flex;
  position: relative;
}

/* Layouts */
.auth-preview-root.layout-split-left-image .auth-preview-shell { flex-direction: row; }
.auth-preview-root.layout-split-right-image .auth-preview-shell { flex-direction: row-reverse; }

.auth-preview-root.layout-centered { background-color: var(--auth-background-color, #f8fafc); }
.auth-preview-root.layout-centered .auth-image-section { display: none !important; }
.auth-preview-root.layout-centered .auth-form-section { width: 100%; background: transparent; }

.auth-preview-root.layout-full-background {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}
.auth-preview-root.layout-full-background::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-full-background .auth-image-section { display: none !important; }
.auth-preview-root.layout-full-background .auth-form-section { width: 100%; z-index: 2; background: transparent; }

.auth-preview-root.layout-minimal { background-color: #ffffff; }
.auth-preview-root.layout-minimal .auth-image-section { display: none !important; }
.auth-preview-root.layout-minimal .auth-form-section { width: 100%; background: #ffffff; }
.auth-preview-root.layout-minimal .auth-card {
  border: none !important;
  box-shadow: none !important;
  background: transparent !important;
  padding: 24px 0 !important;
}

.auth-preview-root.layout-card-left {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}
.auth-preview-root.layout-card-left::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-card-left .auth-image-section { display: none !important; }
.auth-preview-root.layout-card-left .auth-form-section { width: 100%; z-index: 2; background: transparent; justify-content: flex-start; padding-left: clamp(32px, 8vw, 120px); }

.auth-preview-root.layout-card-right {
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}
.auth-preview-root.layout-card-right::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}
.auth-preview-root.layout-card-right .auth-image-section { display: none !important; }
.auth-preview-root.layout-card-right .auth-form-section { width: 100%; z-index: 2; background: transparent; justify-content: flex-end; padding-right: clamp(32px, 8vw, 120px); }

/* Background Section */
.auth-image-section {
  flex: 0 0 var(--auth-image-width, 50%);
  width: var(--auth-image-width, 50%);
  min-height: 100vh;
  position: relative;
  display: flex;
  overflow: hidden;
  background-color: var(--auth-background-color, #0f172a);
  background-image: var(--auth-background-image, none);
  background-size: var(--auth-background-size, cover);
  background-position: var(--auth-background-position, center);
  background-repeat: var(--auth-background-repeat, no-repeat);
}

.auth-image-overlay {
  position: absolute;
  inset: 0;
  z-index: 1;
  background-color: var(--auth-overlay-color, #000000);
  opacity: var(--auth-overlay-opacity, 0.35);
  pointer-events: none;
}

.auth-image-content {
  position: absolute;
  inset: 0;
  z-index: 2;
  display: flex;
  padding: clamp(24px, 4vw, 56px);
}
.auth-image-content.position-top-left { align-items: flex-start; justify-content: flex-start; text-align: left; }
.auth-image-content.position-top-center { align-items: flex-start; justify-content: center; text-align: center; }
.auth-image-content.position-top-right { align-items: flex-start; justify-content: flex-end; text-align: right; }
.auth-image-content.position-center-left { align-items: center; justify-content: flex-start; text-align: left; }
.auth-image-content.position-center { align-items: center; justify-content: center; text-align: center; }
.auth-image-content.position-center-right { align-items: center; justify-content: flex-end; text-align: right; }
.auth-image-content.position-bottom-left { align-items: flex-end; justify-content: flex-start; text-align: left; }
.auth-image-content.position-bottom-center { align-items: flex-end; justify-content: center; text-align: center; }
.auth-image-content.position-bottom-right { align-items: flex-end; justify-content: flex-end; text-align: right; }

.auth-image-text-block { max-width: 480px; }
.auth-image-text {
  margin: 0 0 12px;
  color: var(--auth-image-text-color, #ffffff);
  font-size: clamp(22px, 3vw, 40px);
  font-weight: 800;
  line-height: 1.2;
  letter-spacing: -0.03em;
  text-shadow: 0 4px 16px rgba(0, 0, 0, 0.35);
}
.auth-image-subtext {
  margin: 0;
  color: var(--auth-image-text-color, #ffffff);
  opacity: 0.85;
  font-size: 15px;
  line-height: 1.6;
}

/* Form Section */
.auth-form-section {
  flex: 1 1 auto;
  min-width: 0;
  min-height: 100vh;
  display: flex;
  overflow-y: auto;
  padding: clamp(24px, 4vw, 64px);
  background-color: #f8fafc;
}

.auth-preview-root.form-horizontal-left .auth-form-section { justify-content: flex-start; }
.auth-preview-root.form-horizontal-center .auth-form-section { justify-content: center; }
.auth-preview-root.form-horizontal-right .auth-form-section { justify-content: flex-end; }

.auth-preview-root.form-vertical-top .auth-form-section { align-items: flex-start; }
.auth-preview-root.form-vertical-center .auth-form-section { align-items: center; }
.auth-preview-root.form-vertical-bottom .auth-form-section { align-items: flex-end; }

/* Card */
.auth-card {
  width: 100%;
  max-width: var(--auth-card-width, 460px);
  padding: var(--auth-card-padding, 40px);
  border-radius: var(--auth-card-radius, 20px);
  background-color: var(--auth-card-background, #ffffff);
  opacity: var(--auth-card-opacity, 1);
  border: var(--auth-card-border-width, 1px) solid var(--auth-card-border-color, #e2e8f0);
  box-shadow: var(--auth-card-shadow, 0 20px 45px rgba(15, 23, 42, 0.10));
  backdrop-filter: blur(var(--auth-card-blur, 0px));
  -webkit-backdrop-filter: blur(var(--auth-card-blur, 0px));
  position: relative;
}

.auth-landing-link-bar { margin-bottom: 20px; }
.auth-landing-link {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  color: #64748b;
  font-size: 13px;
  font-weight: 500;
  text-decoration: none;
}
.auth-landing-link:hover { color: #2563eb; }

/* Branding & Logo */
.auth-branding-header { display: flex; flex-direction: column; margin-bottom: 24px; }
.auth-branding-header.auth-logo-pos-left { align-items: flex-start; text-align: left; }
.auth-branding-header.auth-logo-pos-center { align-items: center; text-align: center; }
.auth-branding-header.auth-logo-pos-right { align-items: flex-end; text-align: right; }

.auth-logo-box {
  width: var(--auth-logo-size, 64px);
  height: var(--auth-logo-size, 64px);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  margin-bottom: 12px;
  background-color: var(--auth-logo-bg, transparent);
  border-radius: var(--auth-logo-radius, 50%);
  clip-path: var(--auth-logo-clip, none);
  -webkit-clip-path: var(--auth-logo-clip, none);
}
.auth-logo-shape-square { border-radius: 0px !important; clip-path: none !important; -webkit-clip-path: none !important; }
.auth-logo-shape-rounded { border-radius: 14px !important; clip-path: none !important; -webkit-clip-path: none !important; }
.auth-logo-shape-circle { border-radius: 50% !important; clip-path: circle(50% at 50% 50%) !important; -webkit-clip-path: circle(50% at 50% 50%) !important; }
.auth-logo-shape-ellipse { border-radius: 50% / 35% !important; clip-path: ellipse(50% 38% at 50% 50%) !important; -webkit-clip-path: ellipse(50% 38% at 50% 50%) !important; }
.auth-logo-img { width: 100%; height: 100%; object-fit: cover; }
.auth-logo-fallback {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #2563eb, #4f46e5);
  color: #ffffff;
  font-weight: 800;
  font-size: calc(var(--auth-logo-size, 64px) * 0.38);
}
.auth-brand-title { font-size: 16px; font-weight: 700; color: var(--auth-title-color, #0f172a); }

/* Typography */
.auth-form-header { margin-bottom: 24px; }
.auth-heading {
  margin: 0 0 8px;
  color: var(--auth-title-color, #0f172a);
  font-size: var(--auth-title-size, 32px);
  font-weight: var(--auth-title-weight, 700);
  line-height: 1.25;
  letter-spacing: -0.02em;
}
.auth-subheading {
  margin: 0;
  color: var(--auth-subtitle-color, #64748b);
  font-size: var(--auth-subtitle-size, 15px);
  line-height: 1.5;
}

/* Forms */
.auth-main-form { display: flex; flex-direction: column; gap: 18px; }
.auth-field-group { display: flex; flex-direction: column; gap: 7px; text-align: left; }
.auth-label-row { display: flex; align-items: center; justify-content: space-between; }
.auth-label { font-size: 13.5px; font-weight: 600; color: var(--auth-label-color, #475569); }
.auth-input-wrapper { position: relative; display: flex; align-items: center; width: 100%; }
.auth-input {
  width: 100%;
  height: 46px;
  padding: 0 14px;
  font-family: inherit;
  font-size: 14.5px;
  color: var(--auth-body-color, #0f172a);
  background-color: #ffffff;
  border: 1.5px solid #cbd5e1;
  border-radius: 10px;
  outline: none;
}
.auth-input:focus {
  border-color: #2563eb;
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.14);
}
.auth-input-password-wrapper .auth-input { padding-right: 42px; }
.auth-password-toggle {
  position: absolute;
  right: 12px;
  background: none;
  border: none;
  padding: 4px;
  cursor: pointer;
  color: #64748b;
}
.password-strength-bar {
  height: 4px;
  background: #e2e8f0;
  border-radius: 2px;
  overflow: hidden;
  margin-top: 4px;
}
.password-strength-fill { height: 100%; background: #10b981; }

.auth-checkbox-group { display: flex; align-items: center; margin-top: -4px; }
.auth-checkbox-label { display: inline-flex; align-items: center; gap: 8px; font-size: 13.5px; color: #475569; cursor: pointer; }
.auth-checkbox { width: 17px; height: 17px; accent-color: #2563eb; }

/* Buttons */
.auth-primary-btn {
  width: 100%;
  height: var(--auth-button-height, 48px);
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 0 20px;
  background: var(--auth-button-bg, #2563eb);
  color: var(--auth-button-text, #ffffff);
  border: none;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 15px;
  font-weight: 650;
  cursor: pointer;
  box-shadow: var(--auth-button-shadow, 0 4px 14px rgba(37, 99, 235, 0.28));
  transition: all 0.15s ease;
}
.auth-primary-btn:hover {
  filter: brightness(1.06);
  transform: translateY(-1px);
}

.auth-secondary-btn {
  width: 100%;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: #f1f5f9;
  color: #334155;
  border: 1px solid #e2e8f0;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
}
.auth-secondary-btn:hover { background: #e2e8f0; color: #0f172a; }

.auth-whatsapp-btn {
  width: 100%;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  background: #f0fdf4;
  color: #15803d;
  border: 1.5px solid #bbf7d0;
  border-radius: var(--auth-button-radius, 10px);
  font-family: inherit;
  font-size: 14px;
  font-weight: 650;
  cursor: pointer;
}
.auth-whatsapp-btn:hover { background: #dcfce7; }

.auth-link { color: #2563eb; text-decoration: none; font-size: 13.5px; font-weight: 600; }
.auth-link:hover { text-decoration: underline; }
.auth-footer-nav { display: flex; align-items: center; justify-content: center; gap: 6px; font-size: 14px; color: #64748b; margin-top: 6px; }
.auth-back-center { justify-content: center; }
.auth-back-link { display: inline-flex; align-items: center; gap: 6px; }

/* Social */
.auth-divider { position: relative; text-align: center; margin: 18px 0 14px; }
.auth-divider::before { content: ""; position: absolute; top: 50%; left: 0; right: 0; height: 1px; background: #e2e8f0; }
.auth-divider span { position: relative; padding: 0 12px; background: var(--auth-card-background, #ffffff); color: #94a3b8; font-size: 12.5px; font-weight: 500; }
.auth-social-buttons { display: flex; gap: 10px; }
.auth-social-buttons.auth-social-layout-horizontal { flex-direction: row; }
.auth-social-buttons.auth-social-layout-vertical { flex-direction: column; }
.auth-social-buttons.auth-social-layout-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr)); }
.auth-social-btn {
  flex: 1;
  min-height: 42px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 0 12px;
  background: #ffffff;
  border: 1.5px solid #e2e8f0;
  border-radius: 9px;
  color: #334155;
  font-family: inherit;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
}
.auth-social-btn:hover { background: #f8fafc; border-color: #cbd5e1; }

/* Inline OTP & Standalone OTP */
.auth-inline-otp-section {
  padding: 12px 0 4px;
  border-top: 1px dashed #e2e8f0;
  margin-top: 4px;
}
.otp-delivery-methods { margin-bottom: 20px; text-align: center; }
.otp-delivery-single { margin-bottom: 12px; }
.otp-delivery-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 12px;
  background: #eff6ff;
  color: #1d4ed8;
  border-radius: 8px;
  font-size: 12.5px;
  font-weight: 600;
}
.otp-delivery-label { display: block; font-size: 12.5px; font-weight: 600; color: #64748b; margin-bottom: 8px; }
.otp-delivery-group { display: flex; justify-content: center; gap: 8px; flex-wrap: wrap; }
.otp-delivery-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border-radius: 20px;
  border: 1.5px solid #e2e8f0;
  background: #ffffff;
  font-family: inherit;
  font-size: 12.5px;
  font-weight: 600;
  color: #475569;
  cursor: pointer;
}
.otp-delivery-pill.active { background: #eff6ff; border-color: #3b82f6; color: #1d4ed8; }

.otp-boxes-container { display: flex; align-items: center; justify-content: center; gap: var(--otp-box-gap, 10px); margin: 8px 0 12px; width: 100%; }
.otp-digit-box {
  width: var(--otp-box-width, 48px);
  height: var(--otp-box-height, 54px);
  border-radius: var(--otp-box-radius, 12px);
  border: 2px solid #cbd5e1;
  background-color: #ffffff;
  text-align: center;
  font-family: inherit;
  font-size: var(--otp-font-size, 24px);
  font-weight: 700;
  color: #0f172a;
  outline: none;
  flex-shrink: 1;
}
.otp-digit-box:focus { border-color: #2563eb; box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.18); }

.otp-resend-row { display: flex; align-items: center; justify-content: center; gap: 6px; font-size: 13.5px; color: #64748b; margin-bottom: 4px; }
.otp-resend-btn { background: none; border: none; color: #2563eb; font-family: inherit; font-size: 13.5px; font-weight: 600; cursor: pointer; }
.otp-resend-btn:disabled { color: #94a3b8; cursor: not-allowed; }

/* Custom User CSS */
${config.customCSS || ""}

@media (max-width: 768px) {
  .auth-preview-shell { flex-direction: column !important; }
  .auth-image-section { display: none !important; }
  .auth-form-section { width: 100% !important; padding: 24px 16px !important; }
  .auth-card { padding: 28px 20px !important; max-width: 100% !important; }
}
`;
  }

  /* =======================================================
     STANDALONE JAVASCRIPT RUNTIME FOR ZIP
  ======================================================= */
  function generateStandaloneAppJS() {
    return `/* =========================================================
   AUTH PAGE - STANDALONE RUNTIME
   Generated by Auth Page Builder
========================================================= */

(function () {
  const config = window.AUTH_CONFIG || {};

  document.addEventListener("DOMContentLoaded", () => {
    initNavigation();
    initPasswordToggle();
    initOtpInputs();
    initOtpResend();
    initDeliveryPills();
    initFormSubmit();
  });

  // 1. Navigation between Login / Signup / Forgot Password / OTP
  function initNavigation() {
    document.addEventListener("click", (e) => {
      const navLink = e.target.closest("[data-auth-nav]");
      if (!navLink) return;
      e.preventDefault();

      const targetPage = navLink.dataset.authNav;
      const wrappers = document.querySelectorAll(".auth-page-form-wrapper");
      wrappers.forEach(w => {
        const match = w.dataset.page === targetPage;
        if (w.parentElement && w.parentElement.classList.contains("auth-page-tab-content")) {
          w.parentElement.style.display = match ? "block" : "none";
        } else {
          w.style.display = match ? "block" : "none";
        }
      });

      if (navLink.dataset.otpMethod === "whatsapp") {
        const whatsappPill = document.querySelector('[data-otp-delivery="whatsapp"]');
        if (whatsappPill) whatsappPill.click();
      }
    });
  }

  // 2. Password visibility toggle
  function initPasswordToggle() {
    document.addEventListener("click", (e) => {
      const toggle = e.target.closest("[data-toggle-password]");
      if (!toggle) return;
      e.preventDefault();

      const wrapper = toggle.closest(".auth-input-password-wrapper");
      const input = wrapper ? wrapper.querySelector("input") : null;
      if (!input) return;

      const isPassword = input.type === "password";
      input.type = isPassword ? "text" : "password";
    });
  }

  // 3. OTP Digits Input Auto-advance
  function initOtpInputs() {
    const boxes = document.querySelectorAll(".otp-digit-box");
    boxes.forEach((box, idx) => {
      box.addEventListener("input", () => {
        const val = box.value.replace(/\\D/g, "");
        box.value = val ? val[0] : "";
        if (box.value && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("keydown", (e) => {
        if (e.key === "Backspace" && !box.value && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowLeft" && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowRight" && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("paste", (e) => {
        e.preventDefault();
        const pasteData = (e.clipboardData || window.clipboardData).getData("text").replace(/\\D/g, "");
        if (!pasteData) return;
        const digits = pasteData.split("");
        digits.forEach((digit, i) => {
          if (idx + i < boxes.length) {
            boxes[idx + i].value = digit;
          }
        });
        const nextFocus = Math.min(idx + digits.length, boxes.length - 1);
        if (boxes[nextFocus]) {
          boxes[nextFocus].focus();
        }
      });
    });
  }

  // 4. OTP Resend Countdown
  function initOtpResend() {
    const buttons = document.querySelectorAll("#otpResendButton, #otpResendButtonInline");
    buttons.forEach(btn => {
      let countdown = Number(btn.dataset.countdown) || Number(config.pages?.otp?.resendSeconds) || 30;
      const countdownSpan = btn.querySelector(".otp-countdown-timer");
      btn.disabled = true;

      const timer = setInterval(() => {
        countdown -= 1;
        if (countdownSpan) countdownSpan.textContent = \`(\${countdown}s)\`;
        if (countdown <= 0) {
          clearInterval(timer);
          btn.disabled = false;
          if (countdownSpan) countdownSpan.textContent = "";
        }
      }, 1000);
    });
  }

  // 5. OTP Delivery Method Selector
  function initDeliveryPills() {
    const pills = document.querySelectorAll("[data-otp-delivery]");
    pills.forEach(pill => {
      pill.addEventListener("click", (e) => {
        e.preventDefault();
        pills.forEach(p => p.classList.remove("active"));
        pill.classList.add("active");
      });
    });
  }

  // 6. Form Submission & Real Post-Auth Redirection
  function initFormSubmit() {
    const forms = document.querySelectorAll(".auth-main-form");
    forms.forEach(form => {
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        const redirectUrl = config.redirectUrl || config.urls?.redirectUrl || "https://customerwebsite.com/dashboard";
        
        const submitBtn = form.querySelector('button[type="submit"]');
        if (submitBtn) {
          submitBtn.innerHTML = "<span>Authenticated! Redirecting...</span>";
          submitBtn.disabled = true;
        }

        setTimeout(() => {
          window.location.assign(redirectUrl);
        }, 800);
      });
    });
  }
})();
`;
  }

  /* =======================================================
     INTEGRATION HELPER SCRIPT FOR ZIP
  ======================================================= */
  function generateIntegrationJS(config) {
    const landing = config.urls?.landingPageUrl || "https://customerwebsite.com";
    const redirect = config.urls?.redirectUrl || "https://customerwebsite.com/dashboard";

    return `/* =========================================================
   AUTH PAGE - SOURCE APPLICATION INTEGRATION SCRIPT
   Place this script in your main application: ${landing}
========================================================= */

(function () {
  const AUTH_URL = "./auth/index.html"; // Adjust to where you host index.html
  const REDIRECT_URL = "${redirect}";

  function navigateToAuth(mode = "login") {
    const target = \`\${AUTH_URL}?mode=\${encodeURIComponent(mode)}&redirect=\${encodeURIComponent(REDIRECT_URL)}\`;
    window.location.assign(target);
  }

  // Expose globally
  window.AuthBridge = {
    login: () => navigateToAuth("login"),
    signup: () => navigateToAuth("signup"),
    forgotPassword: () => navigateToAuth("forgotPassword"),
    otp: () => navigateToAuth("otp"),
    redirectUrl: REDIRECT_URL
  };

  document.addEventListener("DOMContentLoaded", () => {
    const loginButtons = document.querySelectorAll("[data-auth-login-trigger]");
    loginButtons.forEach(btn => {
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        navigateToAuth("login");
      });
    });
  });
})();
`;
  }

  /* =======================================================
     INTEGRATION SNIPPET HTML
  ======================================================= */
  function generateIntegrationSnippetHTML(config) {
    const landing = config.urls?.landingPageUrl || "https://customerwebsite.com";
    return `<!-- =======================================================
     SOURCE APPLICATION INTEGRATION SNIPPET
     Insert into your website header or navbar at: ${landing}
======================================================= -->
<div class="user-auth-cta">
  <a href="./auth/index.html" class="btn btn-primary" data-auth-login-trigger>
    Sign In
  </a>
</div>

<!-- Optional Integration Script -->
<script src="./js/integration.js"><\/script>
`;
  }

  /* =======================================================
     STANDALONE INDEX.HTML GENERATOR FOR ZIP
  ======================================================= */
  function generateStandaloneIndexHTML(config) {
    const brandName = Utils.escapeHtml(config.branding?.brandName || "Authentication");
    const activePage = config.activePage || "login";

    const loginHTML = Templates.generateLoginPage(config);
    const signupHTML = Templates.generateSignupPage(config);
    const forgotHTML = Templates.generateForgotPasswordPage(config);
    const otpHTML = Templates.generateOtpPage(config);

    const layout = config.layout || {};
    const layoutType = layout.type || "split-left-image";
    const formHPos = layout.formHorizontalAlignment || "center";
    const formVPos = layout.formVerticalAlignment || "center";

    const imageSection = config.imageSection || {};
    const showBackgroundText = imageSection.showText !== false;
    const bgHeading = Utils.escapeHtml(imageSection.text || "Experience the next generation of authentication.");
    const bgSubtext = Utils.escapeHtml(imageSection.subtext || "Fast, secure, and beautifully customized for your brand.");
    const bgPosClass = `position-${imageSection.textPosition || 'center'}`;

    const landingUrl = config.urls?.landingPageUrl || "";

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${brandName} - Authentication</title>
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  
  <link rel="stylesheet" href="./css/styles.css">
</head>
<body>

  <div class="auth-preview-root layout-${layoutType} form-horizontal-${formHPos} form-vertical-${formVPos}">
    <div class="auth-preview-shell">
      
      <!-- Visual Image / Background Section -->
      <div class="auth-image-section">
        <div class="auth-image-overlay"></div>
        ${showBackgroundText ? `
          <div class="auth-image-content ${bgPosClass}">
            <div class="auth-image-text-block">
              <h2 class="auth-image-text">${bgHeading}</h2>
              ${bgSubtext ? `<p class="auth-image-subtext">${bgSubtext}</p>` : ""}
            </div>
          </div>
        ` : ""}
      </div>

      <!-- Auth Form Section -->
      <div class="auth-form-section">
        <div class="auth-card">
          ${landingUrl ? `
            <div class="auth-landing-link-bar">
              <a href="${Utils.escapeHtml(landingUrl)}" class="auth-landing-link">
                ← Back to Website
              </a>
            </div>
          ` : ""}

          ${Templates.generateLogo(config)}

          <div class="auth-page-container">
            <div class="auth-page-tab-content" style="display: ${activePage === 'login' ? 'block' : 'none'};">
              ${loginHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'signup' ? 'block' : 'none'};">
              ${signupHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'forgotPassword' ? 'block' : 'none'};">
              ${forgotHTML}
            </div>
            <div class="auth-page-tab-content" style="display: ${activePage === 'otp' ? 'block' : 'none'};">
              ${otpHTML}
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>

  <script src="./js/config.js"></script>
  <script src="./js/app.js"></script>
</body>
</html>`;
  }

  /* =======================================================
     README GENERATOR
  ======================================================= */
  function generateReadme(config) {
    return `# ${config.branding?.brandName || "Auth Page"} - Customized Authentication Package

Generated by **Auth Page Builder**.

## Quick Start
1. Open \`index.html\` directly in any modern web browser.
2. The authentication forms (Login, Signup, Forgot Password, OTP) work out-of-the-box.

## Configured URLs
- **Customer Landing / Source URL**: \`${config.urls?.landingPageUrl || "Not configured"}\`
- **Post-Authentication Redirect URL**: \`${config.urls?.redirectUrl || "https://customerwebsite.com/dashboard"}\`

Upon form submission, the authentication page will simulate verification and perform \`window.location.assign("${config.urls?.redirectUrl || "https://customerwebsite.com/dashboard"}")\`.

## Landing Page Integration
To integrate with your website (\`${config.urls?.landingPageUrl || "https://customerwebsite.com"}\`):
- Place the snippet from \`integration-snippet.html\` or load \`js/integration.js\` in your navbar.

## File Structure
\`\`\`
generated-auth-page/
  ├── index.html                  # Main authentication page
  ├── config.json                 # Machine-readable configuration
  ├── integration-snippet.html    # Embed snippet for your landing page
  ├── css/
  │   └── styles.css              # Complete self-contained styling
  ├── js/
  │   ├── config.js               # Embedded JSON configuration
  │   ├── app.js                  # Client runtime & real redirection
  │   └── integration.js          # Landing page integration helper
  ├── assets/                     # All background, logo & icon assets
  └── README.md                   # Documentation
\`\`\`
`;
  }

  /* =======================================================
     MAIN DOWNLOAD FUNCTION (ZIP CREATION)
  ======================================================= */
  async function downloadPackage() {
    if (typeof JSZip === "undefined") {
      alert("JSZip library is loading. Please try again in a moment.");
      return;
    }

    if (Utils.showToast) {
      Utils.showToast("Building customized package...", "info", 2000);
    }

    try {
      const config = getCleanConfig();
      const zip = new JSZip();
      const folder = zip.folder("generated-auth-page");

      const cssFolder = folder.folder("css");
      const jsFolder = folder.folder("js");
      const assetsFolder = folder.folder("assets");
      const bgFolder = assetsFolder.folder("backgrounds");
      const logoFolder = assetsFolder.folder("logos");
      const iconFolder = assetsFolder.folder("icons");

      // Asset mapping for relative paths inside ZIP
      const exportConfig = JSON.parse(JSON.stringify(config));

      // 1. Process Background Image
      if (config.background?.uploadedImage && config.background.uploadedImage.startsWith("data:")) {
        const base64Data = config.background.uploadedImage.split(",")[1];
        if (base64Data) {
          bgFolder.file("background-custom.png", base64Data, { base64: true });
          exportConfig.background.image = "./assets/backgrounds/background-custom.png";
          exportConfig.background.uploadedImage = "./assets/backgrounds/background-custom.png";
        }
      } else if (config.background?.image && !config.background.image.startsWith("data:")) {
        const bgData = await fetchAsset(config.background.image);
        if (bgData) {
          const filename = config.background.image.split("/").pop() || "background.jpg";
          bgFolder.file(filename, bgData);
          exportConfig.background.image = `./assets/backgrounds/${filename}`;
        }
      }

      // 2. Process Logo Image
      if (config.branding?.uploadedLogo && config.branding.uploadedLogo.startsWith("data:")) {
        const base64Data = config.branding.uploadedLogo.split(",")[1];
        if (base64Data) {
          logoFolder.file("logo-custom.png", base64Data, { base64: true });
          exportConfig.branding.logo = "./assets/logos/logo-custom.png";
          exportConfig.branding.uploadedLogo = "./assets/logos/logo-custom.png";
        }
      } else if (config.branding?.logo && !config.branding.logo.startsWith("data:")) {
        const logoData = await fetchAsset(config.branding.logo);
        if (logoData) {
          const filename = config.branding.logo.split("/").pop() || "logo.png";
          logoFolder.file(filename, logoData);
          exportConfig.branding.logo = `./assets/logos/${filename}`;
        }
      }

      // 3. Build config.json
      const configJSON = {
        landingPageUrl: exportConfig.urls?.landingPageUrl || "",
        redirectUrl: exportConfig.urls?.redirectUrl || "",
        authentication: exportConfig.authentication || {},
        branding: exportConfig.branding || {},
        layout: exportConfig.layout || {},
        background: exportConfig.background || {},
        card: exportConfig.card || {},
        typography: exportConfig.typography || {},
        button: exportConfig.button || {},
        social: exportConfig.social || {},
        pages: exportConfig.pages || {}
      };
      folder.file("config.json", JSON.stringify(configJSON, null, 2));

      // 4. Build js files
      jsFolder.file("config.js", `window.AUTH_CONFIG = ${JSON.stringify(configJSON, null, 2)};\n`);
      jsFolder.file("app.js", generateStandaloneAppJS());
      jsFolder.file("integration.js", generateIntegrationJS(exportConfig));

      // 5. Build integration-snippet.html
      folder.file("integration-snippet.html", generateIntegrationSnippetHTML(exportConfig));

      // 6. Build css/styles.css
      cssFolder.file("styles.css", generateStandaloneCSS(exportConfig));

      // 7. Build index.html
      folder.file("index.html", generateStandaloneIndexHTML(exportConfig));

      // 8. Build README.md
      folder.file("README.md", generateReadme(exportConfig));

      // 9. Generate ZIP Blob and trigger download
      const content = await zip.generateAsync({ type: "blob" });
      if (typeof document !== "undefined" && document.createElement) {
        const a = document.createElement("a");
        const url = (typeof URL !== "undefined" && URL.createObjectURL) ? URL.createObjectURL(content) : "#";
        a.href = url;
        a.download = "generated-auth-page.zip";
        document.body.appendChild(a);
        a.click();
        setTimeout(() => {
          if (a.parentNode) document.body.removeChild(a);
          if (typeof URL !== "undefined" && URL.revokeObjectURL && url !== "#") {
            URL.revokeObjectURL(url);
          }
        }, 1000);
      }

      if (Utils.showToast) {
        Utils.showToast("Your authentication package has been downloaded!", "success");
      }
    } catch (err) {
      console.error("ZIP Generation error:", err);
      if (Utils.showToast) {
        Utils.showToast("Failed to generate ZIP package.", "error");
      }
    }
  }

  return {
    downloadPackage,
    generateStandaloneCSS,
    generateStandaloneAppJS,
    generateIntegrationJS,
    generateIntegrationSnippetHTML,
    generateStandaloneIndexHTML,
    generateReadme
  };
});