/* =========================================================
   AUTH PAGE - STANDALONE RUNTIME
   Generated by Auth Page Builder
========================================================= */

(function () {
  let config = window.AUTH_CONFIG || {};

  async function loadConfig() {
    if (typeof fetch !== "undefined") {
      try {
        const response = await fetch("./config/auth-config.json");
        if (response && response.ok) {
          const loadedConfig = await response.json();
          config = Object.assign({}, config, loadedConfig);
          window.AUTH_CONFIG = config;
        }
      } catch (e) {
        // Fetch failed (e.g. local file protocol environment or JSDOM without HTTP server)
      }
    }
    if (!config || Object.keys(config).length === 0) {
      console.error("[Runtime Error] Unable to load exported authentication configuration.");
      showRuntimeError("Unable to load exported authentication configuration.");
      return false;
    }
    return true;
  }

  function showRuntimeError(message) {
    const banner = document.createElement("div");
    banner.className = "auth-runtime-error-banner";
    banner.style.cssText = "position:fixed;top:20px;left:50%;transform:translateX(-50%);z-index:9999;background:#ef4444;color:#ffffff;padding:16px 28px;border-radius:12px;font-family:sans-serif;font-weight:600;box-shadow:0 10px 25px rgba(0,0,0,0.3);text-align:center;";
    banner.textContent = message;
    document.body.appendChild(banner);
  }

  document.addEventListener("DOMContentLoaded", () => {
    if (!config || Object.keys(config).length === 0) {
      showRuntimeError("Unable to load exported authentication configuration.");
      console.error("[Runtime Error] Unable to load exported authentication configuration.");
    }
    initNavigation();
    initPasswordToggle();
    initOtpInputs();
    initOtpResend();
    initDeliveryPills();
    initFormSubmit();

    loadConfig();
  });

  let currentPage = "login";

  function pageFromHash() {
    const rawHash = (window.location.hash || "").replace("#", "").replace("/", "").toLowerCase();
    if (rawHash === "signup") return "signup";
    if (rawHash === "otp") return "otp";
    if (rawHash === "forgot-password" || rawHash === "forgot" || rawHash === "forgotpassword") return "forgotPassword";
    return "login";
  }

  function hashFromPage(page) {
    if (page === "signup") return "#/signup";
    if (page === "otp") return "#/otp";
    if (page === "forgotPassword") return "#/forgot-password";
    return "#/login";
  }

  function showPage(targetPage, updateHash = true) {
    if (!targetPage) return;
    currentPage = targetPage;

    const wrappers = document.querySelectorAll(".auth-page-form-wrapper");
    wrappers.forEach(w => {
      const match = w.dataset.page === targetPage;
      const tabContent = w.closest(".auth-page-tab-content");
      if (tabContent) {
        tabContent.style.display = match ? "block" : "none";
      } else {
        w.style.display = match ? "block" : "none";
      }
    });

    if (updateHash) {
      const targetHash = hashFromPage(targetPage);
      if (window.location.hash !== targetHash) {
        try {
          history.pushState(null, "", targetHash);
        } catch (e) {
          window.location.hash = targetHash;
        }
      }
    }
    console.log("[Runtime] Navigation: Page switched to '" + currentPage + "'");
  }

  // 1. Navigation between Login / Signup / Forgot Password / OTP
  function initNavigation() {
    document.addEventListener("click", (e) => {
      const navLink = e.target.closest("[data-auth-nav], a[href*='#']");
      if (!navLink) return;

      let targetPage = navLink.dataset ? navLink.dataset.authNav : null;
      if (!targetPage && navLink.getAttribute) {
        const href = navLink.getAttribute("href") || "";
        const cleanHref = href.replace("#", "").replace("/", "").toLowerCase();
        if (cleanHref === "signup") targetPage = "signup";
        else if (cleanHref === "otp") targetPage = "otp";
        else if (cleanHref === "forgot" || cleanHref === "forgot-password" || cleanHref === "forgotpassword") targetPage = "forgotPassword";
        else if (cleanHref === "login") targetPage = "login";
      }

      if (targetPage) {
        e.preventDefault();
        showPage(targetPage, true);

        if (navLink.dataset && navLink.dataset.otpMethod === "whatsapp") {
          const whatsappPill = document.querySelector('[data-otp-delivery="whatsapp"]');
          if (whatsappPill) whatsappPill.click();
        }
      }
    });

    window.addEventListener("hashchange", () => {
      showPage(pageFromHash(), false);
    });
    window.addEventListener("popstate", () => {
      showPage(pageFromHash(), false);
    });

    showPage(pageFromHash(), false);
  }

  // 2. Password visibility toggle
  function initPasswordToggle() {
    document.addEventListener("click", (e) => {
      const toggle = e.target.closest("[data-toggle-password]");
      if (!toggle) return;
      e.preventDefault();

      const wrapper = toggle.closest(".auth-input-password-wrapper");
      const input = wrapper ? wrapper.querySelector("input") : null;
      if (!input) return;

      const isPassword = input.type === "password";
      input.type = isPassword ? "text" : "password";
    });
  }

  // 3. OTP Digits Input Auto-advance
  function initOtpInputs() {
    const boxes = document.querySelectorAll(".otp-digit-box");
    boxes.forEach((box, idx) => {
      box.addEventListener("input", () => {
        const val = box.value.replace(/[^0-9]/g, "");
        box.value = val ? val[0] : "";
        if (box.value && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("keydown", (e) => {
        if (e.key === "Backspace" && !box.value && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowLeft" && idx > 0) {
          boxes[idx - 1].focus();
        } else if (e.key === "ArrowRight" && idx < boxes.length - 1) {
          boxes[idx + 1].focus();
        }
      });

      box.addEventListener("paste", (e) => {
        e.preventDefault();
        const pasteData = (e.clipboardData || window.clipboardData).getData("text").replace(/[^0-9]/g, "");
        if (!pasteData) return;
        const digits = pasteData.split("");
        digits.forEach((digit, i) => {
          if (idx + i < boxes.length) {
            boxes[idx + i].value = digit;
          }
        });
        const nextFocus = Math.min(idx + digits.length, boxes.length - 1);
        if (boxes[nextFocus]) {
          boxes[nextFocus].focus();
        }
      });
    });
  }

  // 4. OTP Resend Countdown
  function initOtpResend() {
    const buttons = document.querySelectorAll("#otpResendButton, #otpResendButtonInline");
    buttons.forEach(btn => {
      let countdown = Number(btn.dataset.countdown) || Number(config.pages?.otp?.resendSeconds) || 30;
      const countdownSpan = btn.querySelector(".otp-countdown-timer");
      btn.disabled = true;

      const timer = setInterval(() => {
        countdown -= 1;
        if (countdownSpan) countdownSpan.textContent = `(${countdown}s)`;
        if (countdown <= 0) {
          clearInterval(timer);
          btn.disabled = false;
          if (countdownSpan) countdownSpan.textContent = "";
        }
      }, 1000);
    });
  }

  // 5. OTP Delivery Method Selector
  function initDeliveryPills() {
    const pills = document.querySelectorAll("[data-otp-delivery]");
    pills.forEach(pill => {
      pill.addEventListener("click", (e) => {
        e.preventDefault();
        pills.forEach(p => p.classList.remove("active"));
        pill.classList.add("active");
      });
    });
  }

  // 6. Form Submission & Input Validation Pipeline
  function showFormError(form, msg) {
    if (typeof window.showToast === "function") {
      window.showToast(msg, "error");
    }
    let errBox = form.querySelector(".auth-form-error-box");
    if (!errBox) {
      errBox = document.createElement("div");
      errBox.className = "auth-form-error-box";
      errBox.style.cssText = "background: rgba(239, 68, 68, 0.1); border: 1px solid rgba(239, 68, 68, 0.3); color: #f87171; padding: 10px 14px; border-radius: 8px; font-size: 13px; margin-bottom: 16px;";
      form.insertBefore(errBox, form.firstChild);
    }
    errBox.textContent = msg;
    errBox.style.display = "block";
  }

  function clearFormError(form) {
    const errBox = form.querySelector(".auth-form-error-box");
    if (errBox) errBox.style.display = "none";
  }

  function validateFormInputs(form) {
    clearFormError(form);
    const formId = form.id || "";

    // A. Signup Form Validation
    if (formId === "authSignupForm") {
      const name = (form.querySelector("#signupName")?.value || "").trim();
      const email = (form.querySelector("#signupEmail")?.value || "").trim();
      const pass = form.querySelector("#signupPassword")?.value || "";
      const confirmPass = form.querySelector("#signupConfirmPassword")?.value || "";
      const terms = form.querySelector("#signupTerms");

      if (!name) {
        showFormError(form, "Please enter your full name.");
        return false;
      }
      if (!email || !email.includes("@")) {
        showFormError(form, "Please enter a valid email address.");
        return false;
      }

      // Password policy validation
      const policy = config.passwordPolicy || {};
      const minLen = Number(policy.minLength) || 8;
      const minNums = Number(policy.minNumbers) || 1;
      const minSpecials = Number(policy.minSpecialChars) || 1;
      const allowedSpecials = policy.allowedSpecialChars || "!@#$%^&*()_+-=[]{}|;:,.<>?";
      let specialCount = 0;
      for (let i = 0; i < pass.length; i++) {
        if (allowedSpecials.indexOf(pass[i]) !== -1) specialCount++;
      }

      if (pass.length < minLen) {
        showFormError(form, `Password must be at least ${minLen} characters long.`);
        return false;
      }
      if (policy.requireUppercase !== false && !/[A-Z]/.test(pass)) {
        showFormError(form, "Password must contain at least one uppercase letter.");
        return false;
      }
      if (policy.requireLowercase !== false && !/[a-z]/.test(pass)) {
        showFormError(form, "Password must contain at least one lowercase letter.");
        return false;
      }
      if (policy.requireNumber !== false && ((pass.match(/[0-9]/g) || []).length < minNums)) {
        showFormError(form, `Password must contain at least ${minNums} number(s).`);
        return false;
      }
      if (policy.requireSpecialChar !== false && specialCount < minSpecials) {
        showFormError(form, `Password must contain at least ${minSpecials} special character(s).`);
        return false;
      }
      if (pass !== confirmPass) {
        showFormError(form, "Passwords do not match.");
        return false;
      }
      if (terms && !terms.checked) {
        showFormError(form, "You must accept the Terms of Service to create an account.");
        return false;
      }
    }

    // B. Login Form Validation
    if (formId === "authLoginForm") {
      const ident = (form.querySelector("#loginIdentifier")?.value || "").trim();
      const pass = form.querySelector("#loginPassword")?.value || "";
      if (!ident || !pass) {
        showFormError(form, "Please enter your identifier and password.");
        return false;
      }
    }

    // C. OTP Form Validation
    if (formId === "authOtpForm") {
      let otpVal = "";
      const singleBox = form.querySelector("#otpCode");
      if (singleBox) {
        otpVal = singleBox.value.trim();
      } else {
        const digitBoxes = form.querySelectorAll(".otp-digit-box");
        otpVal = Array.from(digitBoxes).map(b => b.value).join("").trim();
      }
      const expectedOtp = config.pages?.otp?.staticOtp || "123456";
      if (!otpVal || (otpVal !== "123456" && otpVal !== expectedOtp)) {
        showFormError(form, "Invalid verification code. Please enter 123456.");
        return false;
      }
    }

    return true;
  }

  function initFormSubmit() {
    const forms = document.querySelectorAll(".auth-main-form");
    forms.forEach(form => {
      form.addEventListener("submit", (e) => {
        e.preventDefault();
        
        // 1. Validate Form Inputs - STOP ON FAILURE
        if (!validateFormInputs(form)) {
          console.warn("[Auth] Form submission halted due to validation failure.");
          return;
        }

        const formId = form.id || "";
        const otpEnabled = config.pages?.login?.otpEnabled !== false;

        // Forgot Password form handling - Show success toast and remain on page without redirecting
        if (formId === "authForgotPasswordForm") {
          console.log("[Auth] Forgot password request submitted successfully.");
          if (typeof window.showToast === "function") {
            window.showToast("Password reset email sent successfully.", "success", 4000);
          }
          return;
        }

        // If Signup succeeds and OTP is enabled, route to OTP verification screen before redirect!
        if (formId === "authSignupForm" && otpEnabled) {
          console.log("[Auth] Signup validation successful. Routing to OTP verification screen.");
          if (typeof window.showToast === "function") {
            window.showToast("Account details validated! Please verify OTP.", "info", 3000);
          }
          showPage("otp", true);
          return;
        }

        const baseRedirect = config.redirect || {};
        const customerLanding = config.urls?.landingPageUrl || config.landingPageUrl || "";
        const targetRedirect = baseRedirect.redirectUrl || config.redirectUrl || config.urls?.redirectUrl || customerLanding || "/dashboard";
        const redirectConfig = Object.assign({}, baseRedirect, {
          redirectUrl: targetRedirect,
          successMessage: formId === "authOtpForm" ? "OTP verified successfully." : (baseRedirect.successMessage || "Authentication completed successfully.")
        });
        
        const submitBtn = form.querySelector('button[type="submit"]');
        if (submitBtn) {
          submitBtn.innerHTML = "<span>Authenticated! Redirecting...</span>";
          submitBtn.disabled = true;
        }

        // 2. Trigger Centralized Redirect Service ONLY ON SUCCESS
        const service = window.RedirectService || window.redirectService;
        if (service && typeof service.resetGuard === "function") {
          service.resetGuard();
        }
        if (service && typeof service.execute === "function") {
          service.execute(redirectConfig, { force: true });
        } else {
          setTimeout(() => {
            if (redirectConfig.openInNewTab) {
              window.open(redirectConfig.redirectUrl, "_blank", "noopener,noreferrer");
            } else {
              window.location.assign(redirectConfig.redirectUrl);
            }
          }, redirectConfig.delay || 0);
        }
      });
    });
  }
})();
